- middlewares/index.js
So solve #56 fully, we need to take care of this setting from [docs](https://www.npmjs.com/package/cors#enabling-cors-pre-flight):
>credentials: Configures the Access-Control-Allow-Credentials CORS header. Set to true to pass the header, otherwise it is omitted.
Problem mentioned [here](https://discordapp.com/channels/673083527624916993/735598747949465640/764489829332811796)
Read more here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
> Credentials set to true for Access-Control-Allow-Credentials #56

- .eslintrc.js
- models/users.js
- test/integration/healthController.test.js
- test/integration/usersController.test.js
- test/unit/middlewares/contentTypeCheck.test.js
Solves #63 
- Throw error from model functions
- Added `this.skip()` to the tests which were failing because of lack of test suite as suggested by @ankurnarkhede 
Feel free to suggest changes. Thank you! 😄
> Throw err from model functions instead of returning them

- middlewares/index.js
OPTIONS call was undergoing a check with the content-type header and failing as a result ISSUE-73
Closes #73
> Fix content-type check after CORS setup

- controllers/pullRequestsController.js
- services/githubService.js
I did the changes for getting the selected page value from user
> pagination capability for PRs API

- scripts/tests/testIntegration.sh
- scripts/tests/testUnit.sh
As per this issue https://github.com/Real-Dev-Squad/website-backend/issues/32, the firestore emulator would keep running even after the tests are done running.
This change fixes --
- Firestore emulator is stopped after the tests are done.
- Remove unnecessary teardown step of erasing data.
We don't need to erase data because firestore emulator does not persist it by default.
If we want to persist data, we have to use `emulators:import` and `emulators:export`. 
Ref:
- [Install, configure and integrate Local Emulator Suite](https://firebase.google.com/docs/emulator-suite/install_and_configure)
- [Test your Cloud Firestore Security Rules](https://firebase.google.com/docs/firestore/security/test-rules-emulator)
> Fix firestore emulator issue

- config/development.js
- The cookie is now being set for `localhost` domain when user is working in development mode.
- The user is redirected to `http://localhost:3000/healthcheck` after successful login.
> Fixed localhost response

- CONTRIBUTING.md
- package.json
- Changed the scripts for testing on windows. ( Works for linux and macOS also)
- `npm run test-integration` and `npm run test-unit` will run the Integration tests and Unit tests correspondingly.
- Fixes #158
> Scripts updated to run tests on windows

- models/tasks.js
> Changing compound query for `/tasks/self` so that manual indexing is not required

- controllers/authController.js
- middlewares/authenticate.js
- scripts/tests/testIntegration.sh
- test/integration/authController.test.js
The `sameSite` attribute of cookie is set to `lax`. Fixes #196
> Sets sameSite attribute of cookie as lax

- .gitignore
- CONTRIBUTING.md
- README.md
- config/custom-environment-variables.js
- config/default.js
- config/test.js
- package-lock.json
- package.json
- scripts/local-test.js
- test/utils/cleanDb.js
- utils/firestore.js
We will no longer need to deal with `firestore-private-key.json`
The existing tests will most likely break, because we are changing how we create our firestore admin object.
Updated the tests for the same, please check.
In order to deploy, it's a good practice to use env variables for keeping sensitive data like keys away from the actual code.
This will let us remove having to create a firestore-private-key.json file and manage it for keys.
Now, package.json can have these changes:
\- `"start": "echo $FIRESTORE_CONFIG_DATA > firestore-private-key.json && node server.js",`
\+ `"start": "node server.js",`
Closes #311
> Remove firestore-private-key.json usage

- README.md
- nyc.config.js
- package.json
- scripts/tests/tdd-files-list.txt
- scripts/tests/tdd.sh
Closes #492 
A developer can now set the files (with wildcards) and run `yarn tdd:watch` and make all the tests pass.
Also, we should make sure that our coverage from `yarn test` reaches a minimum of 50%, before enabling the flag
> feature(TDD): Add TDD setup and soft-enable 50% coverage markers 

- README.md
The goal of this section is for debugging proposes, when build fails at production but runs fine locally.
> add production section in readme

- constants/roles.js
- controllers/members.js
- middlewares/validators/members.js
- models/members.js
- routes/members.js
- test/fixtures/user/user.js
- test/integration/members.test.js
* Added a new role archived in ROLES constant
* Added a query param includeArchived(default value false)
* By default only unarchived users are returned. We can use includeArchived = true flag to get all users
* Updated and added integration test for /members endpoint
* Updated swagger doc for /members endpoint
* Rename all occurrences of archivedMember to archived
Closes #601 
Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/672
> Modifies /members to return only unarchived users (by default)

- controllers/users.js
- models/users.js
- routes/users.js
- test/fixtures/user/user.js
- test/integration/users.test.js
- #661 
* Endpoint : `PATCH /users/add-default-archived-role`
* Added model,route,controller methods. Default archived = `false` role will be added to all users where either roles DNE or role.archived DNE
* Added integration test for this endpoint
* Load tested this endpoint with `5000` users (all without archived property in roles map). 
Time taken ≈ `15-20 sec` . 
Breakdown : 5000 reads(≈4s) + 5000 updates(≈12s) 
Closes #651 
Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/672
> Adds an endpoint to add default archived role only where it does not exists

- models/users.js
- test/integration/members.test.js
- test/integration/users.test.js
- test/utils/deleteRoles.js
- test/utils/deleteRolesObject.js
- #681 
* Updated addOrUpdate model function
* Added deleteRoles and deleteRolesObject test util to delete all/specified roles
* Fixed integration tests /users/add-default-archived-role using delete utils
* Updated member integration tests since now we have only 1 kind of unarchived user : the user with archived = false
Closes #660 
Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/672
> Adds default archived role for new users

- routes/users.js
Add the `/users/add-default-archived-roles` route
This got deleted while resolving merge conflicts
> fix: Added /users/add-default-archived-roles route

- models/members.js
> **Warning**
> This PR can only be merged after #662 and after `PATCH /users/add-default-archived-role` has been executed
- #662
* Updated members model with firestore query to fetch unarchived users
Closes #652
Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/601#issuecomment-1219781528
> Uses firestore query to fetch only unarchived users

- routes/tasks.js
- utils/cache.js
- Created a cache module to get and store API responses from the cache pool for a controller.
- Cached responses from /tasks endpoint using the cache module.
> Made a in memory cache module and added it to /tasks endpoint

- middlewares/validators/tasks.js
closes #743 
level and category key is added into validators of task object as part of adding new feature to display tags on each task on status website
Update website-api-contract/tasks/
https://github.com/Real-Dev-Squad/website-status/pull/322
> added level and categories key in validators-middleware for task object

- middlewares/validators/tasks.js
- test/integration/tasks.test.js
Closes #739 
Priority was added to the task schema and made a required parameter, allowing the priority data to be supplied when a post request is made when submitting the data from the dashboard site.
> added priority to task schema

- controllers/tasks.js
- routes/tasks.js
- test/fixtures/user/user.js
- test/integration/tasks.test.js
closes #764
- added an endpoint that can be used to assign tasks to the user, the user can hit this endpoint and a task will get assigned to them if it is available
- We can remove the assignTask middleware when this PR gets merged
> added an endpoint for task assignment

- controllers/tasks.js
- models/logs.js
- test/integration/tasks.test.js
- Will create a new log and save to the database about the event
- called the `addlog` API to create a log for the event
- Response after a successful call
- If the user is trying to change the status to `MERGED`, it will be forbidden.
- If `status` is already `COMPLETED` and the user is trying to change only the `percentCompleted` to less than 100, it will give a bad request.
- If `status` is not `COMPLETED` and the user is trying to change the `percentCompleted` to 100, it will give a bad request.
> Status changed by User on the task will be logged

- controllers/userStatus.js
- middlewares/validators/userStatus.js
- models/userStatus.js
- routes/userStatus.js
- test/fixtures/userStatus/userStatus.js
- test/integration/userStatus.test.js
- utils/userStatus.js
Closes the [issue](https://github.com/Real-Dev-Squad/website-data-models/issues/17)
This is a stacked PR and should be merged after https://github.com/Real-Dev-Squad/website-backend/pull/879
> Future Status Update

- middlewares/validators/user.js
- models/users.js
- routes/users.js
- test/integration/users.test.js
- Min(1) and Max(100) limit on number of users requested using query-param size 
- Validation on query params _size_ and _page_ using middelware **joi**
```javascript
size: /^[1-9]\d?$|^100$/
page: /^\d$|^[1-9]\d?/
``` 
- No limit on number of users requested using query-param size 
- No validation on query params _size_ and _page_
[Issue: 842](https://github.com/Real-Dev-Squad/website-backend/issues/842)
```javascript
GET /users?size=<value>&page=<value>
```
<small>params: \*size, page\? </small>
- Failing Tests have nothing to do with this PR.
- [API Contract](https://github.com/Real-Dev-Squad/website-api-contracts/pull/102)
> feat: users ep GET request, query-param size validation

- middlewares/validators/discord.js
- test/fixtures/discord/discord.js
Closes #919
- Fixed the Discord Model Validator i.e. changed the `generationTime` field to `timestamp`
**Data Model Reference**
https://github.com/Real-Dev-Squad/website-data-models/tree/main/discord
- Fixed the fixtures of API as well for testing
> Fixed request body of discord bot API

- controllers/extensionRequests.js
- routes/index.js
- test/integration/extensionRequests.test.js
Convention bugs like.
- Referring to the model extension requests as `extensionRequest` and `extensionRequests` in some other places.
- Majorly using `/extension-requests` instead of `/extensionRequest` as the latter creates confusion and also doesn't follow the API conventions.
> convention bugs fixed

- controllers/external-accounts.js
- models/external-accounts.js
- routes/external-accounts.js
- test/fixtures/external-accounts/external-accounts.js
- test/integration/external-accounts.test.js
- test/unit/models/external-accounts.test.js
#912 
- Created a GET endpoint to get the data of the external account
- **GET** `/external-accounts/:token`
- Data returned from the API
- Added a duplicate token check in `POST` `/external-accounts` API
```json
{
"message": "Data returned successfully",
"attributes": "<object>"
}
```
> Created GET API for External Accounts

- routes/auth.js
Resolves #839 
Added a new route `/auth/github/login` which will handle the login with GitHub
Now we don't need to set CLIENT_ID in hardcode the login URL `https://github.com/login/oauth/authorize?client_id=<CLIENT_ID>` we can just hit `/auth/github/login` and it will handle the login based on the clientId and secrets set in the config file of the user
> Add new route for login with github

- test/utils/addUser.js
fixes #949 
addUser is an async function however its return type was not
wrapped in a promise which is why the when using the function with
`await` there was a lint warning that showed up that saying `await
is not needed`, but without await the function won't work
properly.
> fix: Incorrect return type to addUser causes lint warning

- controllers/issues.js
- controllers/tasks.js
- middlewares/validators/tasks.js
- models/tasks.js
- models/users.js
- routes/index.js
- routes/issues.js
- services/githubService.js
- services/issuesService.js
- test/unit/models/users.test.js
- test/unit/services/githubService.test.js
- The following PR introduces Issue API routes and controllers for the [One-Click task conversion feature](https://github.com/Real-Dev-Squad/todo-action-items/issues/92).
- `GET` route to fetch all the issues on GitHub across all repositories from RDS's organization.
- `POST` route that receives updates from RDS organization webhook when there's a change in any issue.
- Issues controller to:
- Fetch and send issues
- Receive issue event changes and update associated task if found.
- The changes also include:
- Models to fetch:
- Task associated with an issue id 
-  Retrieve RDS user information by GitHub username.
- Test cases to validate:
- GitHub service to fetch issues  
- Users model to fetch RDS user information with GitHub username
> Feat: One-Click Issue to Task Conversion

- test/fixtures/standup/standup.js
- test/integration/standup.test.js
This pull request includes tests for the standup API. The standup API has three parts: 
1. **Marking a user for standup**, which is a superuser feature. This allows a superuser to mark a user as monitored for standup, meaning that the user will be expected to give a standup update every day.
2. **Saving a user's standup**, which is an authenticated route. This allows a user to save their daily standup update.
3. **Getting a user's standup**, which is accessible throughout as in the future it will be retrieved via Discord slash commands. This allows anyone to view a user's standup updates.
The tests are being pushed and skipped for now to ignore GitHub warnings since the feature does not exist yet. These tests will promote test-driven development during the development of the feature, …
> add and skip tests for the mark standup api

- controllers/issues.js
- services/githubService.js
- services/issuesService.js
- test/unit/services/githubService.test.js
This PR closes the following [issue to search for issues across RDS repositories](https://github.com/Real-Dev-Squad/todo-action-items/issues/144)
- Users can search for specific issues using search strings that are passed as request query parameter
- Depending on the value of the query parameter, the relevant API from GitHub is called.
- If the query param is empty, then the issues are fetched from GitHub issues API
- Else, the issues are fetched from the GitHub search API
- Existing service to fetch issues is leveraged with an additional parameter for search string.
> Feature: Search issues using GitHub Search API

- models/monitor.js
- test/fixtures/trackedProgress/index.js
- test/integration/monitor.js
- test/integration/trackedProgresses.js
- utils/monitor.js
- utils/progresses.js
This PR adds tests for the Tracked Progress Collection. The tests cover various scenarios such as creating tracked progress documents, handling errors, retrieving progress documents, and asserting response data.
With this we also make the queries more specific in the util file by specifying the `type`.
Please find the parent ticket [here](https://github.com/Real-Dev-Squad/website-backend/issues/1076)
> Adds tests for tracked progress route

- .github/workflows/test.yml
At times when there is something wrong in test it doesn't stop and timesout after 360 mins or 6 hr, as that is the GitHub actions timeout, It consumes our free limit of runtime provided for actions 
On average out workflow tests are completed in under 2 mins
> Set github actions timeout to 5 mins

- controllers/tasks.js
- models/tasks.js
Issue ticket : https://github.com/Real-Dev-Squad/website-status/issues/607
This PR fixes a bug where `assigneeRdsInfo` was not being added to the `tasks` object correctly. The issue was caused by asynchronous code, where tasks were being fetched using `tasks.fetchTasks()`, which returns a list of Promises. However, the code was not waiting for all Promises to resolve before adding `assigneeRdsInfo` to the tasks.
To fix this, I updated the code to use `Promise.all` to wait for all Promises to resolve before adding `assigneeRdsInfo` to the tasks.
> Fix bug with adding `assigneeRdsInfo` to tasks

- models/users.js
- test/unit/models/users.test.js
This PR is a sub-part of a bigger feature
The feature overview: 
we need to add an in_discord role with the value false to each user in RDS which in turn is a sub-part of the discord syncing API. In the mentioned API we plan to add the discord joined date to every user in the server and change their in_discord role to true.
Test Coverage: 
Lines written by me: 486-491
> add a function to fetch all users from db and write tests

- controllers/events.js
fixes #1173 
Used proper `userId` and `roomId` to get stored in a token.
> [Live-Site] Add correct roomId and userId in authToken

- controllers/users.js
- test/integration/usersFilter.test.js
API Link : https://api.realdevsquad.com/users/search?state=IDLE&state=ACTIVE&state=OOO
The current above API returns personal details like Phone , E-mail and GitHub Access tokens. In this PR we are removing user personal details from the response.
**Test Coverage**
**Screenshot**
Before
After
> Remove user personal details filters data

- services/discordService.js
- test/unit/services/discordService.test.js
This pull request aims to enhance the Real Dev Squad backend by integrating and consuming the previously developed Discord Role Removal API [Real-Dev-Squad/discord-slash-commands/pull/82] . The integration allows the backend to utilize the API's functionality to remove roles from users in Discord seamlessly.
1. **API Integration**: The Real Dev Squad backend has been updated to integrate with the Discord Role Removal API. 
2. **API Request**: The backend can now send a DELETE request to the Discord Role Removal API when triggered by the corresponding action or event. The request includes the user and role identifiers required to perform the role removal operation in Discord.
3. **Error Handling**: Error handling with try and catch block will be maintained in the function consuming this …
> Feature: Consume Discord Role Removal API in Real Dev Squad Backend

- models/tasks.js
Closes #1254
Currently, self API of tasks is failing because there is no field of startedOn in some tasks so for the temporary solution it is been removed for a permanent solution the issue is mentioned below.
- https://github.com/Real-Dev-Squad/website-backend/issues/1257
> Remove orderBy from self tasks api

- controllers/userStatus.js
- middlewares/validators/userStatus.js
- models/userStatus.js
- routes/userStatus.js
- test/fixtures/user/user.js
- test/integration/taskBasedStatusUpdate.test.js
- test/unit/middlewares/userStatusValidator.js
- test/unit/models/taskBasedStatusUpdate.test.js
Closes the 1st task of the ticket https://github.com/Real-Dev-Squad/website-backend/issues/1248
- As of now users can change their status to idle active or OOO from my site. moving forward this will be decided from their task if they have a task assigned on their name or a task in progress they are active else they would be considered idle. Now the users have the flexibility to mark themselves as idle or active from my site on their own which will be removed. This script will Identify all the users who are idle based on their task status. If they have a task in assigned or in_progress they will be counted as active else they will be counted as idle and returned in the response of this script. This is a one time script going forward when a new task is assigned user will be marked active …
> Auto script to detect idle users ids

- middlewares/validators/userStatus.js
- test/integration/userStatus.test.js
Parent Ticket Id - https://github.com/Real-Dev-Squad/website-backend/issues/1184
**Changes** :
> Remove the option of marking oneself as idle or active

- constants/cacheKeys.js
- routes/taskRequests.js
- routes/tasks.js
- test/fixtures/cache/cache.js
- test/unit/middlewares/cache.test.js
- test/unit/utils/cache.test.js
- utils/cache.js
closes Issue: 
-  #1278 
Description:
1. Add a new data store to save all the keys generated for a particular cached API endpoint under a common key
>     eg: /tasks?page=2&size=9 / AND /tasks?page=10&size=10 will be saved as a set under a common key '__cache__ALL_TASKS'.
2. Add a middleware to evict cache data based on given common keys. 
>     eg: /tasks?page=2&size=9 / AND /tasks?page=10&size=10 cached 
3. Use the said middleware for when there's a write on tasks model
4. Increase expiry time of fetch all tasks api to 10mins.
Test coverage:
> Add middleware to invalidate cache

- test/integration/taskBasedStatusUpdate.test.js
- test/unit/middlewares/userStatusValidator.js
- test/unit/models/taskBasedStatusUpdate.test.js
- test/unit/utils/userStatusValidator.test.js
Issue ticket - https://github.com/Real-Dev-Squad/website-backend/issues/1295
The updates in this PR modify the tests to handle batch updates of both idle and active users. Currently, we execute a batch update script that identifies idle users and marks them as idle, which adds them to the pool of idle users. Now, we also want to remove users from the idle list if they are active. Therefore, in addition to identifying new idle users, this PR ensures that active users are correctly removed from the idle state. The changes made here are limited to updating the test cases. The subsequent PR will include the actual code changes, and the tests that are currently skipped will be uncommented in that PR.
> Update Batch scripts Tests to handle active users

- controllers/external-accounts.js
- models/users.js
- test/integration/external-accounts.test.js
This pull request addresses the issue of synchronizing the "in_discord" role for users in our system based on their presence in the Discord server. The changes introduced in this pull request will enable us to update the "in_discord" role for each user, ensuring accurate representation of their Discord status within our platform.
**Test Coverage:**
| File name | Lines | Branches | Functions | Statements | Excluded lines |
| --------------------- | ------- | -------- | --------- | ---------- | ------------------------------------------- |
| /models/users.js | 66.02% | 69.23% | 62.74% | 65.42% | ...,526-540,563-564,584-585,614-615,621-622 |
| /controllers/external-accounts.js | 75.51% | 68.75% | 85.71% | 75.51% | 8-24,42-43 |
> FEATURE: change `in_discord` role based on condition

- config/default.js
- controllers/auth.js
- routes/auth.js
- test/integration/auth.test.js
- test/utils/github.js
`/auth/github/login?redirectURL="any-realdevsquad-website"`
Adds `redirectURL` query params, to redirect to the specified URL
Closes: https://github.com/Real-Dev-Squad/website-backend/issues/1213
> Add redirectURL params in github/login route

- controllers/tasks.js
- test/integration/taskBasedStatusUpdate.test.js
Closes 
- #1310
We currently update user status only for tasks when they are marked as completed. However, we also need to update user status for other statuses like NEEDS_REVIEW,  IN_REVIEW etc. to mark users as idle/active.
This feature is hidden behind a feature flag.
Testing Stats: 
Controllers
> Include all tasks state such as NEEDS_REVIEW , IN_REVIEW etc. for Marking Users Idle/ Active

- test/unit/middlewares/cache.test.js
- utils/cache.js
Fixes: #1305
Description: 
For caching: 
1. This PR adds a check to verify if the controller layer sets the status code in the range 2xx before caching the response.
For Invalidation: 
1. Currently we were invalidating the cache before passing the control to controller function. 
2. This PR makes necessary changes to make the invalidation after the controller function is executed. It also makes sure the call was successful by checking the status code. 
Test coverage:
> Cache new response if successful 

- controllers/external-accounts.js
- models/users.js
- test/fixtures/discordResponse/discord-response.js
- test/integration/external-accounts.test.js
- test/unit/models/users.test.js
closes: #1233 
When the 'in_discord' flag is set to true for a user, their 'archived' role should be updated to true as well.
Currently, there is no automated process to update the 'archived' role when the 'in_discord' flag is set to true for a user. The 'archived' role remains unaffected even if 'in_discord' is true.
Create a script that runs periodically and checks the 'in_discord' flag for each user. If the 'in_discord' flag is true for a user, the script should update their 'archived' role to true.
The script should be written in a programming language with access to the necessary database or user management system. The script should perform the following steps:
1. Connect to the user database or user management system.
2. Retrieve a list of all users.
3. For each user in the list, …
> Script to Update 'archived' Role When 'in_discord' is True

- controllers/userStatus.js
- models/userStatus.js
- test/integration/userStatus.test.js
Closes 
- #1291
The Current Route on Status Update doesn't gives any metrics. We would like to see the metrics so that the super user is aware of the no of users updated and modified. 
The current PR updates the model function to send the necessary details in the response.
Proof on Local 
**Before** 
**After**
Testing Stats:
Models 
Controllers
> Adds Metrics for Users Status Update Route

- controllers/tasks.js
- middlewares/validators/userStatus.js
- test/integration/taskBasedStatusUpdate.test.js
- test/integration/userStatus.test.js
- test/unit/middlewares/userStatusValidator.test.js
- #1224 
- [] Yes 
None
Description:
This pull request (PR) aims to removes the userStatus flag, which is currently in use to track user status based on task. The feature is now stable and has been in prod since more than 3 weeks and as confirmed with Ankush we can remove this feature flag.
Testing Stats:
Controllers:
Validator
> Remove userStatus feature flag

- models/userStatus.js
- test/integration/taskBasedStatusUpdate.test.js
- test/unit/models/taskBasedStatusUpdate.test.js
- test/unit/utils/taskBasedStatusUpdates.test.js
- utils/userStatus.js
- #1381 
None
Presently, if a user designates themselves as "Out of Office" (OOO) starting from today, they are unable to transition back to an "Idle" or "Active" status once the OOO period concludes. In the past, users had the ability to manually set themselves as "Active" or "Idle" directly on the site. However, due to the transition towards a task-based status update we now run a script periodically we need to check if OOO period is over then we need to change their status accordingly.
Model file : models/userStatus.js
utils file : utils/userStatus.js
> include OOO completed users in status update

- controllers/members.js
- test/integration/members.test.js
**Why do we need to keep the body (reason) optional to the issue/ ticket #1214 ?**
- If we don't keep the body optional, the current archiving process will break because we don't have to Input field in the front-end for the body `reason`,
In the future scope, we will make the body(reason) a required field.
This PR aims to make the 
body an optional field to not break the current working process in prod, and the body (reason) can be passed optional, and yet the authorized users can fetch the logs of `archived-details`.
**Test case coverage and result:**
> Refactor: keeping body optional in archiving details in the archiving process

- controllers/discordactions.js
- models/discordactions.js
- scripts/tests/testUnit.sh
- services/dataAccessLayer.js
- test/fixtures/user/user.js
- test/integration/discordactions.test.js
- test/unit/models/discordactions.test.js
- test/unit/services/dataAccessLayer.test.js
- test/unit/utils/helper.test.js
- utils/helper.js
This pull request addresses the need to include the `isMember` field in the API response for the `GET discord-actions/groups` endpoint. This field is necessary to provide information about whether the current user is a specific group member. This information is crucial for displaying the appropriate content on the group's page, specifically the right panel that lists all the groups the current member is a part of.
This PR also does refactoring and moves additional features under a feature flag.
Fixes: #1388 
```
{
"message": "Roles fetched successfully!",
"groups": [
{
"id": "mExFFXEJo2YL8XBbdYJ1",
"date": {
"_seconds": 1689838197,
"_nanoseconds": 139000000
},
"rolename": "group-developers",
"roleid": "1131488158979194902",
"createdBy": "eCITJh08tFpYvq4SDa1d",
"count": 1,
"firstName": …
```
> Add isMember Field to API Response for Group Membership

- constants/events.js
- controllers/events.js
- middlewares/validators/events.js
- models/events.js
- routes/events.js
- test/fixtures/events/event-codes.js
- test/integration/events.test.js
- test/unit/models/events.test.js
Closes #1424
In this PR I have created a API to generate event codes.
This API creates a event code entry/object/entity in event code collection and and stores reference of it's id to event collection.
Query params - id
Req body - {eventCode: "<String, required>", role: "String, required"}
Tests coverage
//unit
//controllers
//utils
//routes
> [Live-Site] feat: create generate event code API

- controllers/extensionRequests.js
- middlewares/validators/extensionRequests.js
- models/extensionRequests.js
- routes/extensionRequests.js
- test/integration/extensionRequests.test.js
- test/unit/utils/queryParser.test.js
- utils/extensionRequests.js
- utils/queryParser.js
Issue: https://github.com/Real-Dev-Squad/website-dashboard/issues/430
- Currently we are able to filter api data based on only one value for a query param eg:  `?q=status:APPROVED`. This PR allows us to filter the data based on multiple values eg: `?q=status:APPROVED+PENDING`
- This PR also adds pagination support for the api. To get paginated result we would have to pass the required page size `?size=10`.
- This PR also adds a functionality to sort the data based on `created time`.eg: `?order=asc`
- Adds a new utility function to parse [RDS query language](https://github.com/Real-Dev-Squad/website-backend/pull/1419#pullrequestreview-1581088590)
- The feature is under a feature flag. To access, please use `?dev=true` query param.
- Please also review this PR which changes the query param …
> Adds pagination to extension request list

- controllers/users.js
- middlewares/validators/user.js
- test/integration/users.test.js
- test/unit/middlewares/users-validator.test.js
**Problem Statement:**
The legacy API endpoint, previously located at `/members/archiveMembers/${id}`, has been deprecated. The new endpoint for this functionality is now available at `/users/${id}/temporary/data` ([updated API endpoint](https://github.com/Real-Dev-Squad/website-members/pull/549/files#diff-3b3e89342fdb3bc17dfd7a2647442154ca1b61f5d70a7244d715c9132aa52785)).
**Proposed Solution:**
This pull request addresses the task of remaking the "Add logs" feature for archived details, similar to ([Issue #1329](https://github.com/Real-Dev-Squad/website-backend/pull/1329)), using the updated API endpoint.
**Changes Made:**
Added `reason` as a body parameter (optional) in the existing function `validateUpdateRoles`, which is now being utilized in the `archived-details` logs.
**Test Case …
> Feat: added reason (optional) in the archiving process

- README.md
Updated Readme with `yarn install --frozen-lockfile ` to avoid `yarn.lock ` to unexpectedly updated with an unknown future version of a dependency.
> update readme with yarn frozen lockfile flag

- controllers/tasks.js
- test/integration/tasks.test.js
Users are able to move their task status to VERIFIED even if the percentage completed is not 100%. This PR adds a validation to let only the tasks which has percentage completed 100% to be moved to VERIFIED.
> Allow task status update to VERIFIED iff percentage completed is 100.

- models/tasks.js
- test/integration/tasks.test.js
- test/unit/models/tasks.test.js
closes #1456 
**Concerned endpoint:** `https://api.realdevsquad.com/tasks?status=<STATUS>&dev=true&assignee=<assignee>`
**Issues:**
1. If provided assignee doesn't exist in database, the endpoint returns all tasks matching other search conditions.
2. No support for getting tasks from multiple assignee.
**What are the changes**
Endpoint impacts:
No breaking changes to endpoint. Assignee query parameter can now accept multiple comma separated values.
`https://api.realdevsquad.com/tasks?status=IN_PROGRESS&dev=true&assignee=firstassignee,secondassignee`
1. **Error handling in case of single assignee search:** If assignee isn't present in database, it now returns empty tasks data. (Though the issue ticket asks for "No tasks found" response, this change has been discussed with @sahsisunny ).
2. …
> Error Handling and Multiple Assignee Search Terms for /tasks Endpoint

- controllers/discordactions.js
- models/discordactions.js
- routes/discordactions.js
- services/discordService.js
- test/fixtures/discordactions/discordactions.js
- test/integration/discordactions.test.js
This pull request introduces a new feature: Sync discord group in Firestore. This API will check if any group `id` is changed it will update it and if there is any new role which is not stored in the Firestore will add that role. 
**Changes Made:**
* Added a new discordActions controller function, `syncDiscordGroupRolesInFirestore`, which gets all the discord roles in Discord.
* Then checks if any role with same name exists in Firestore `discord-roles` collection but its ID is not updated then it updates the ID
* But there are any roles which are not saved in the Firestore then it creates documents of those roles in Firestore collection. 
* it gives all the roles saved in Firestore in the response.
* Added detailed JSDoc documentation for the `updateGroupRole` and …
> sync discord groups in firestore

- controllers/auth.js
- test/unit/services/generateAuthToken.test.js
- test/unit/utils/generateUniqueToken.test.js
- utils/generateUniqueToken.js
This PR addresses the **Token Generation** part of the above mentioned issue as follows:
Initially a unique token was being sent when user authenticate themselves using **Scan with QR**, but while hitting the API endpoints we do need the session cookie of the user to Authorize each request.
Instead of sending a unique token, rds-session cookie is being sent as a part of the response, which can be used to make successful API calls.
Test coverage stats:
> REFACTOR: return rds-session token in response

- test/unit/middlewares/data-access-layer.test.js
- test/unit/utils/data-access.test.js
- utils/data-access.js
**Description**:
This pull request introduces a new feature: Data Access Middleware. This middleware allows for fine-grained control over which fields are exposed in API responses based on user roles and predefined rules.
**Changes Made**:
- Added a new middleware function, `dataAccessMiddleware`, which takes an `options` object as its configuration.
- The `options` object can include an array of `rules`, specifying which fields should be removed based on allowed user roles and key paths.
- The middleware iterates through the specified rules and removes sensitive fields from the response if the user does not have the required role.
- Added detailed JSDoc documentation for the `dataAccessMiddleware` function, including usage examples.
**Testing**:
> Create a data access middleware

- controllers/users.js
- routes/users.js
- services/users.js
Set of removals done in this PR
- The route for removing nickname-synced field of the user document.
- The controller function of the route.
- The service function that removes the **nickname_synced** field from all the users using a batch update
> remove nickname-synced field API

- controllers/discordactions.js
- models/discordactions.js
- routes/discordactions.js
- test/fixtures/discordactions/discordactions.js
- test/integration/discordactions.test.js
- test/unit/models/discordactions.test.js
Description: 
This API deletes the roleId from the discord and backend database
> Created api endpoint to remove role from a member group

- models/userStatus.js
- test/fixtures/userStatus/userStatus.js
- test/integration/userStatus.test.js
- test/unit/utils/time.test.js
- test/unit/utils/userStatus.test.js
- utils/time.js
- utils/userStatus.js
- #1579 
None
Currently, when a user selects OOO from website-my, the timestamp for the chosen date is stored as 00:00:00 UTC. However, a problem arises when the user chooses OOO for just one day, as both the from and until timestamps are set to 00:00:00 UTC, resulting in them being equal and causing a OOO duration of 0 milliseconds. To address this issue, the from and until timestamps for a single-day OOO should be set to 00:00:00 UTC and 23:50:59 UTC, respectively, to avoid conflicts when updating the user's Discord nickname.
Unit Tests :
models/userStatus.js
utils/userStatus.js
Integration Tests:
> Update time stamp for OOO

- models/userStatus.js
- test/fixtures/userStatus/userStatus.js
- test/unit/models/userStatus.js
- #1606
None
When a user's status is set to "Out of Office" (OOO) and they decide to cancel their OOO status, the future status associated with the cancellation is not being reset as expected. Upon canceling the OOO, the future status should be automatically reset.
Unit Tests :
`models/userStatus.js`
> Bug / Reset future status when canceling OOO

- controllers/tasksRequests.js
- models/taskRequests.js
- test/fixtures/task-requests/task-requests.js
- test/unit/models/taskRequests.js
- https://github.com/Real-Dev-Squad/website-status/issues/920
- Previously the task request models had mandatory field of taskId. But with the new type of task requests we have added some more fields, one among them is request type which can have values [ASSIGNMENT,CREATION]. 
- In the type CREATION task id is not mandatory. CREATION is supposed to create the task when super user approves it.
- Since this API previously used to fetch task details based on the given taskId, In CREATION requests taskId would be undefined. 
- This PR adds checks to return only the old task requests when dev flag is false and the new ones with newly added fields when the dev flag is true. 
Note: 
This is just a stop gap solution until migration of all the old task request model is done.
After migration this …
> Changes to support task assignment requests model in GET /taskRequests

- controllers/extensionRequests.js
Reviewed log should show the timestamp when the request was reviewed and not when it was created
NA
- https://github.com/Real-Dev-Squad/website-my/pull/511
> Chore : Added timestamp of logs in self ER request

- controllers/users.js
- middlewares/validators/user.js
- test/fixtures/user/user.js
- test/integration/users.test.js
- test/unit/middlewares/user-validator.test.js
- test/unit/services/users.test.js
To prevent a user from updating their roles as it may cause a security concern and allow only those user who want to join as maven and have not joined Discord yet
NA
**When in_discord is false**
**When in_discord is true** 
**Tests Stats:**
> Discard user to udpate their roles

- middlewares/validators/user.js
- test/unit/middlewares/user-validator.test.js
Developer Name: @vinit717 
Issue Ticket Number:- #1661 
**Description**
Added "-" in regex to validate the username and write its test case
Any special instructions for the deployment (none)
**Before Changes:**
**After Changes:**
**Test Stats:**
> Added "-" in validation for generating username

- models/users.js
- test/integration/users.test.js
Issue: #1654
By adding new role data with the existing roles in the Firestore document then the previous roles got removed. This change will ensure that the update only affects the specified role without affecting other roles that may already be present.
NA
**Tests Stats**
> Fix Issue: Update Specific Role Without Removing Others

- controllers/tasks.js
- test/fixtures/tasks/tasks.js
- test/integration/tasks.test.js
Date: 22-11-23
----
- Closes #1709 
Adds createdAt field to tasks model when creating a new Task (Initially createdAt and updatedAt will be same)
Adds updatedAt field to tasks model when tasks are being updated
Following Migration script PR to be merged https://github.com/Real-Dev-Squad/website-backend/pull/1715
- https://github.com/Real-Dev-Squad/website-data-models/pull/58 [data-models]
-https://github.com/Real-Dev-Squad/website-api-contracts/issues/167 [api-contracts]
Creating new task
After Updating a task
> Add createdAt and updatedAt fields for task collection

- controllers/tasks.js
- services/tasks.js
- test/integration/tasks.test.js
Date: 23-11-23
----
- Closes #1712 
Migration script for adding createdAt and updatedAt fields in task documents
API CALL: 
```
POST: /tasks/migration
body: {
"action": "ADD",
"field": "CREATED_AT+UPDATED_AT"
}
```
Test coverage
> I1712 migration script to add created at updated at in task doc

- controllers/tasks.js
- test/integration/tasks.test.js
Reverts Real-Dev-Squad/website-backend#1703
dev to main: https://github.com/Real-Dev-Squad/website-backend/pull/1704
Reason: removing feature flag without running 1 time script break things on prod
> Revert "Remove feature flag: replace 'COMPLETED' with 'DONE' from 'updateTaskStatus' function"

- models/tasks.js
- test/integration/tasks.test.js
Date: 24-11-23
----
- Closes #1720 
Change task orderBy to updatedAt field for paginations API
The requirement is to show the data in desc order of updatedAt field
> I1720 change task orderby desc order

- controllers/cloudflareCache.js
- test/integration/cloudflareCache.test.js
Date: 27/11/2023
Developer Name: @sumitd94 
----
- https://github.com/Real-Dev-Squad/website-my/issues/530
the `count` key in the response was returning the total number of counts the user has used for purging the cache, but ideally it should be giving us the remaining count the user has left with in purging cache
> fix: update remaining count key

- controllers/discordactions.js
- models/discordactions.js
- test/fixtures/discordactions/discordactions.js
- test/integration/discordactions.test.js
- test/unit/models/discordactions.test.js
Date: `30 November 2023`
----
Currently anyone can pass any discord role id and get privileges. This pr fixes that.
> Restricts what roles can be added to user discord profile

- constants/taskRequests.ts
- controllers/tasksRequests.js
- models/taskRequests.js
- test/integration/taskRequests.test.js
- test/unit/models/task-requests.test.js
Date: 20 November 2023
----
- #1588 
- Adds a models function which updates all the existing task requests documents to have usersCount(number of people requesting the same task) and createdAt. These fields are used for sorting. 
- Updates the existing create task requests models function to have usersCount.
- https://github.com/Real-Dev-Squad/website-data-models/pull/55
- https://github.com/Real-Dev-Squad/website-api-contracts/pull/164
- https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/task-requests
> Migration script to add users count and also updates create task request for users count

- constants/constants.ts
- constants/tasks.ts
- controllers/tasks.js
- middlewares/validators/tasks.js
- routes/tasks.js
- test/integration/tasks.test.js
- test/unit/middlewares/tasks-validator.test.js
Date: 9 Dec 2023
----
- #1699 
Adds a route and controller function which returns discord Id of users who are active with tasks but have not filled in progress updates on task details page.
- https://github.com/Real-Dev-Squad/website-api-contracts/pull/173
> Adds route and controller for missed update user list api

- middlewares/validators/tasks.js
- test/integration/tasks.test.js
- test/unit/middlewares/tasks-validator.test.js
Date: 14 Dec 2023
Developer Name: Randhir
----
- #1776
This pull request updates the PATCH request in the /tasks endpoint, After this update User will not be able to change their task status to AVAILABLE. Only a super user can change the status to available in that case the assignee will be removed and set to null.
Integration Tests
Unit Tests
Code Coverage
> Enhancement : Restrict Task Status Change to Available for Task assigned to Self

- controllers/users.js
- routes/users.js
- test/integration/restricted.test.js
- test/integration/users.test.js
- test/unit/middlewares/contentTypeCheck.test.js
Date: 14/02/2024
---
Closes #1909 
We want to disable developers from updating the data from the UI. So for that as a temporary solution, we have to add an API that calls discord slash commands get the member roles from discord, and return if a user is a developer or not. 
If any developer likes to ensure that his/her data stays up-to-date in Real Dev Squad, they need to create a [profile service](https://github.com/Real-Dev-Squad/sample-profile-service/blob/main/README.md).
> API to check if a user is a developer

- middlewares/authorizeUsersAndService.ts
- routes/discordactions.js
- routes/external-accounts.js
- routes/tasks.js
- routes/userStatus.js
- routes/users.js
- test/integration/authorizeUsersAndService.test.ts
Date: 26-02-2024
Developer Name: Pavan Bhat
---
This ticket does not close the issue but solves a part of [this issue](https://github.com/Real-Dev-Squad/cron-jobs/issues/60)
Updated certain middlewares for specific routes, intended for migration to a cron job. This modification facilitates authentication and authorization through a unified middleware, accommodating both cookie-based authentication and authentication via public and private keys for APIs triggered within the cron job context.
Route's Modified: 
- **User Status Update:**
- Endpoint: `/users/status/update`
- Method: `PATCH`
- **Idle (No Auth & Auto):**
- Endpoint: `/users/status?aggregate=true`
- Method: `GET`
- **Batch Idle:**
- Endpoint: `/users/status/batch`
- Method: `PATCH`
- **Endpoint:** …
> Enabling Authentication and Authorization from a Single Middleware for Cookie and Bearer Token-Based Flows

- controllers/discordactions.js
- test/fixtures/discordactions/discordactions.js
- test/integration/discordactions.test.js
Date: 6 March 2024
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/website-backend/issues/1939
This PR contains 2 fixes.
1. Users cannot add roles that are not stored in the database.
2. If a role is stored in the database, users can only add those with a group prefix.
https://github.com/Real-Dev-Squad/website-backend/assets/56365512/f2b719e4-7f34-438e-bedf-603a547dcbd8
The failing test case is also failing on locally and has nothing to do with my changes.
> Bug : Added checks to validate user groups

- controllers/auth.js
- controllers/staging.js
- models/members.js
- models/users.js
- services/users.js
Date: 23/03/2024
Developer Name: Mehul Chaudhari
---
#1929 
Some APIs which update the user documents now don't update the `updated_at` field in the user document which says when the document was updated latest. 
Not adding or updating tests, because we are just updating the `updated_at` field while updating the `user` document, and most of the API's do not return the `updated_at` field in the response.
</details>
> update updated_at in user documents whenever user data is updated

- routes/discordactions.js
Date: 18-03-2024
Developer Name: Pavan Bhat
---
#1989 
_Removed Middleware for Reference:_
This route `discord-actions/nicknames/sync` is behind a middleware accessing `req.userData` which would only be available if the call is made through website-dashboard. As we move these routes to a cronjob, we need to remove this check. Have verified `req.userData` is not being used for this route's controller and is safe to remove
<details>
</details>
<details>
</details>
> Removed checkIsVerifiedDiscord for discord-actions/nicknames/sync API

- controllers/tasks.js
- middlewares/validators/discordactions.js
- middlewares/validators/tasks.js
- middlewares/validators/utils.ts
- models/tasks.js
- routes/tasks.js
- test/integration/tasks.test.js
Date: 2/04/2024
Developer Name: @MehulKChaudhari 
---
- https://github.com/Real-Dev-Squad/todo-action-items/issues/215
When tasks are assigned to users that are not in a "DONE" state and when they leave the server, they become orphan tasks, which get missed and become untrackable. So this API filters out such tasks and marks them `BACKLOG`
<details>
</details>
For staging and production, we will need to add these composite indexes.
> feat: Filter orphan tasks and mark them BACKLOG

- controllers/external-accounts.js
- models/tasks.js
- test/fixtures/discordResponse/discord-response.js
- test/integration/external-accounts.test.js
Date: 13/04/2024
Developer Name: @MehulKChaudhari 
---
- #2005 
Reimplement the logic to filter the orphan tasks, now we have a separate cron job and API to filter the orphan tasks but we should do it when we are marking user archived: true. 
we are reimplementing this so that we have data consistency, with the current implementation there might be a case where the user is archived earlier and their undone tasks are not marked BACKLOG till the next corn runs to filter the tasks. 
This is a re-implementation of - https://github.com/Real-Dev-Squad/website-backend/pull/1996
> 2005 reimplement orphan tasks filteration logic

- models/tasks.js
- test/integration/external-accounts.test.js
Date: 22/04/2-24
Developer Name: @MehulKChaudhari 
---
#2005 bug 
The tasks were not filtered because I was using assigneeID to search the tasks but the actually field in DB is `assignee: userID`.  This confusion was caused because `/tasks` data has a assigneeID assigneeID is not a tasks document field. Assignee is the actual
<details>
</details>
> Fix: orphan tasks bug in staging. 

- constants/requests.ts
- middlewares/validators/extensionRequestsv2.ts
- middlewares/validators/requests.ts
- test/fixtures/extension-requests/extensionRequests.ts
- test/unit/middlewares/extensionRequests.test.ts
- typeDefinitions/global.d.ts
- types/extensionRequests.d.ts
- #2019
In the PR, a new middleware was added to create extension requests through the request router. This middleware will facilitate the creation of extension requests for the user.
<details>
</details>
| File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|-----------------------------|---------|----------|---------|---------|-------------------|
| extensionRequestsv2.ts      |   100   |   100    |   100   |   100   |                   |
| requests.ts                 | 87.75   | 44.44    |   100   | 85.71   | 18,27-30,50,59    |
In the next PR, a controller will be added to handle the extension request creation.
> Added middleware for extension request for /request route

- constants/requests.ts
- controllers/oooRequests.ts
- controllers/requests.ts
- middlewares/validators/extensionRequestsv2.ts
- middlewares/validators/requests.ts
- models/requests.ts
- test/fixtures/extension-requests/extensionRequests.ts
- test/unit/middlewares/extensionRequests.test.ts
- test/unit/models/requests.test.ts
- typeDefinitions/global.d.ts
- types/extensionRequests.d.ts
- #2018 
Refactor request controller and model functions to add more request types, such as extension requests and task creation requests in the future.
<details>
</details>
| File                               | Branch Coverage (%) | Function Coverage (%) | Statement Coverage (%) | Line Coverage (%) | Missing Lines          |
|------------------------------------|---------------------|-----------------------|------------------------|-------------------|------------------------|
| models/requests.ts                 | 86.31               | 89.74                 | 100                    | 85.05             | 50-151,180-181         |
| controller/oooRequests.ts          | 85                  | 78.57                 | 100                    | 83.33 …
> REFACTOR: request controller and model functions

- constants/requests.ts
- constants/taskRequests.ts
- constants/urls.ts
- middlewares/validators/requests.ts
- middlewares/validators/taskRequests.ts
- test/fixtures/taskRequests/taskRequests.ts
- test/integration/requests.test.ts
- test/unit/middlewares/taskRequests.test.ts
- types/taskRequests.d.ts
Date: 27 June 2024
Developer Name: @sahsisunny 
---
Closes [#2042 ]
This PR introduces a middleware to facilitate the task creation requests to the unified `/request` API endpoint. The middleware ensures that all task creation requests are redirected appropriately and handled uniformly through the new endpoint.
Documentation will be updated after the successful migration of all endpoints.
<details>
</details>
<details>
</details>
This middleware is the first step in the migration process, and subsequent PRs will address the actual redirection logic and handle the deprecation of the old endpoints.
> Add Middleware for Migrating Task Creation Requests to /request API Endpoint

- constants/requests.ts
- controllers/requests.ts
- controllers/taskRequestsv2.ts
- test/integration/requests.test.ts
- #2042
I have migrated the task creation request to a universal /request route. This involves updating the controller function to utilize constants for messages, ensuring better maintainability and consistency across the codebase.
<details>
</details>
<details>
</details>
> feat: added controllere for TCR

- controllers/users.js
- middlewares/validators/user.js
- models/users.js
- https://github.com/Real-Dev-Squad/members-site/issues/152
- Add the `roles` query parameter to the `/users` API to filter users data.
- currently, the roles query param only accepts the `members` role, it will be fixed with the new onboarding flow that @tejaskh3 is working on.
> add roles query param in /users api to get all members

- middlewares/checkCanGenerateDiscordLink.ts
- test/integration/discordactions.test.js
- closes #2102 
Make a change for discord verification middleware to allow to generate link till 31 August 2024.
> Hotfix to extend date to generate discord link

- controllers/applications.ts
- models/applications.ts
- routes/applications.ts
Date: `22 August, 2024`
Developer Name: @yeshavyas27
---
- Closes #2094 
This PR removes the applications/batch endpoint and its related code that added createdAt and status fields to the applicants' collection.
Unit Tests:
Integration Tests:
The original PR for #2094 is #2092 (closed as 2 PR for the same issue were created due to miscommunication)
> Removed migration script at applications/batch endpoint that added createdAt and status fields to applicants collection

- controllers/applications.ts
- models/applications.ts
- routes/applications.ts
- test/integration/application.test.ts
- test/unit/models/application.test.ts
Date: `27 August, 2024`
Developer Name: @yeshavyas27
---
- Closes #2094 
This PR removes the applications/batch/update endpoint and its related code that added createdAt and status fields to the applicants' collection. Tests for this API are also removed.
Unit Tests:
Integration Tests:
> Removed migration script at applications/batch/update that added createdAt and status fields to applicants collection

- models/applications.ts
- test/unit/models/application.test.ts
Date: `23rd August, 2024`
Developer Name:  @Favourokerri 
---
- Closes #2093
This pull request enhances the getUserApplications query by sorting the user's applications in descending order based on their creation date (createdAt). The query now ensures that the most recently created application appears first in the list. Additionally, only the first application in the sorted array is returned, making it easier to display the user's most recent application
<details>
Only the first and most recent application is returned
</details>
<details>
<summary>Screenshot 2</summary>
</details>
</details>
> fixed getUserApplications to-fetch-latest-application

- controllers/users.js
- middlewares/validators/user.js
- models/users.js
- test/integration/users.test.js
- test/unit/middlewares/user-validator.test.js
- test/unit/models/users.test.js
Date: 09-09-2024
Developer Name: Shubham Raj
---
#2110
The PR add a new property `disabled_roles` in the users object with an array of string value; these string value will an enum value for now  but the list can be extended to more roles as well. 
For now these value are these, which are basically the the property name of the roles
`[ “super_user”, “members”];`
An Empty Array `[ ]` : means that no roles have been toggled off / privileges are downgraded.
`[‘super_user’]`: means that the `super_user` role has been restricted.
`[ “super_user”, “members”]`: means that both `super_user` as well as `member` roles have been restricted.
In the Data Access Layer we mutate the user Object, to be very specific about the function, in the `fetchUser` function, this way all the instances where we …
> [Feat] Extends Toggle privilege feature allowing other roles to be Toggled off

- controllers/extensionRequests.js
- test/integration/extensionRequests.test.js
- test/integration/multilpleExtensionRequest.test.js
---
Closes #2137 
1. Keep the `dev=true` flow (allows to create multiple extension requests) and remove the `dev=false` flow
2. Merge the multiple extension requests tests with extension requests test
<details>
<summary>Create first extension request</summary>
</details>
<details>
<summary>Create extension request when existing exists with PENDING status</summary>
</details>
<details>
<summary>Create extension request when existing exists with APPROVED status</summary>
</details>
NA
> Remove dev feature flag for POST /extension-requests API

- controllers/logs.js
- test/integration/logs.test.js
---
Closes #2136 
1. Remove 400 Bad request error when `dev` query param is not true
2. Remove dev query param from next page link
3. Update integration tests
NA
NA
> Remove dev feature flag for GET /logs API

- controllers/requests.ts
- middlewares/validators/requests.ts
- test/integration/requests.test.ts
- test/unit/middlewares/requests.test.ts
---
Closes #2139 
1. Remove `dev` query param from the next page link being set in the response
2. Make the `dev` query param optional in the request validator
3. Update integration tests
<details>
<summary>Get requests with `dev` FF</summary>
</details>
<details>
<summary>Get requests without `dev` FF</summary>
</details>
NA
> Remove dev feature flag for GET /requests API

- middlewares/validators/requests.ts
- test/integration/requests.test.ts
- test/unit/middlewares/requests.test.ts
- types/requests.d.ts
---
Closes #2140 , #2141 
1. Remove the 400 Bad Request error when `dev` query param is not true for both create and update requests API
2. Update integration tests
NA
NA
> Remove dev feature flag for POST /requests and PUT /requests/:id APIs

- models/profileDiffs.js
Date: 08 Oct 2024
---
#2204 
This PR addresses an issue where the email and phone fields were not being obfuscated in the `profileDiff` response. It adds checks to obfuscate the email and phone fields before sending the response back to the client. This ensures that sensitive user data is protected.
No documentation updates were needed as this was an internal bug fix related to obfuscation.
This fix is applied globally and is not gated by a feature flag.
No database changes were required for this fix.
There are no breaking changes associated with this update.
This fix has been tested locally.
> Fix: Obfuscate email and phone in profileDiff response

- config/custom-environment-variables.js
- config/default.js
- constants/subscription-validator.ts
- controllers/subscription.ts
- controllers/users.js
- middlewares/authenticateProfile.js
- middlewares/devFlag.ts
- middlewares/validators/subscription.ts
- middlewares/validators/user.js
- package.json
- routes/index.ts
- routes/subscription.ts
- routes/users.js
- test/config/test.js
- test/fixtures/subscription/subscription.ts
- test/integration/profileDiffsDev.test.js
- test/integration/subscription.test.js
- test/integration/users.test.js
- test/unit/middlewares/authenticateProfile.test.js
- test/unit/middlewares/devFlag.test.js
- test/unit/middlewares/subscription-validator.test.js
- test/unit/middlewares/user-validator.test.js
- types/global.d.ts
- yarn.lock
Date: 17-Oct-2024
Developer Name: @vikasosmium, @tejaskh3, @MayankBansal12 
---
#2123 (Please don't close this issue)
#2126 
#2206 
#2124 
#2201 
#2212 
<details>
</details>
> Dev to Main Sync

- constants/discordRoles.ts
- controllers/external-accounts.js
- test/integration/external-accounts.test.js
- test/unit/utils/removeDiscordRole.test.js
- utils/removeDiscordRole.js
Date: 01/10/24
Developer Name: Shobhan Sundar Goutam
---
- Closes <https://github.com/Real-Dev-Squad/discord-slash-commands/issues/234>
This PR fixes the first issue which is removing unverified role from discord when user runs /verify and connects their RDS Discord
<details>
https://github.com/user-attachments/assets/98d0a3e3-9a34-429a-81d6-3dd79625eb0a
</details>
<details>
</details>
> remove unverified role on /verify

- controllers/subscription.ts
- middlewares/validators/subscription.ts
- test/fixtures/subscription/subscription.ts
- test/unit/middlewares/subscription-validator.test.js
- types/global.d.ts
Date: 24 oct, 2024
Developer Name: @tejaskh3 
---
closes https://github.com/Real-Dev-Squad/website-backend/issues/2228
The issue is we were using phone in "KEYS_NOT_ALLOWED" but while taking user phone inputs we took phoneNumber as field, which exposed phone number publicly. So, in this PR we are fixing the issue motioned above.
</details>
This is just an fix in which we changed  name of a field in test cases as well.
> [HOT FIX] change phoneNumber to phone to hide it from APIs

- controllers/arts.js
- routes/arts.ts
- test/integration/arts.test.js
Date: 18-Nov-2024
---
- #2219 
This PR includes adding one route to fetch user art and comment, deprecation warning to use the new route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/199
**Coverage**
> Added new route to fetch user Art

- models/userStatus.js
- services/discordMembersService.js
- test/unit/middlewares/authenticate.test.js
- utils/discord-actions.js
Date: 17-11-2024
Developer Name: Mayank Bansal
---
#2217 
- Added unit test cases for authentication middleware inside `authenticate.test.js`
- Due to a missing import statement was getting an error while running tests. Fixed the error by adding the missing config statement in three files.
<details>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
> feat: add unit tests for authentication middelware 

- controllers/discordactions.js
- models/discordactions.js
- routes/discordactions.js
- services/discordService.js
- test/integration/discordactions.test.js
- test/unit/models/discordactions.test.js
- test/unit/services/discordService.test.js
Date: 04 Nov 2024
Developer Name: @VaibhavSingh8
---
- Closes #2191 
This PR implements the ability for super users to delete Discord groups through the `/groups` endpoint on the dashboard site. This feature allows for better group management.
- Added the `deleteGroupRole` model function to handle the soft deletion of group roles in the Firestore database.
- The deletion is implemented as a soft delete, setting `isDeleted: true` along with deletion metadata.
- Implemented controller logic to handle deletion requests, verify role existence, log deletion events for audit, and manage responses with appropriate status codes.
- Added comprehensive test coverage for both success and error scenarios.
<details> …
> Feat: Super users can delete discord group roles

- controllers/tasks.js
- routes/tasks.js
- routes/users.js
- test/integration/tasks.test.js
- test/integration/users.test.js
Date:  18 Dec 2024
Developer Name: Kavya Rishi @vikasosmium 
---
- https://github.com/Real-Dev-Squad/website-backend/issues/2263
- #2219 
- https://github.com/Real-Dev-Squad/website-backend/pull/2284
- #2293 
<details>
> Dev to main sync 

- controllers/extensionRequests.js
- routes/extensionRequests.js
- test/integration/extensionRequests.test.js
Date: 18-Dec-2024
---
- #2219 
This PR includes adding one GET route for User Extension Req. and a deprecation warning for the old self route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/206
**Coverage**
> Added new GET Route for User Extension Req.

- controllers/discordactions.js
- middlewares/validators/discordactions.js
- models/discordactions.js
- routes/discordactions.js
- test/unit/models/discordactions.test.js
Date: `8th December, 2024`
Developer Name: @Achintya-Chatterjee 
---
- Closes #2129 
Added pagination, where only a subset of groups is loaded initially. Additional groups should load dynamically as the user scrolls or interacts with the page, ensuring smooth performance. The page would remain responsive and efficient, regardless of the total number of groups.
<details>
- `Without dev=true`
https://github.com/user-attachments/assets/d10d8817-9072-46b1-8408-9fe76d1aabb7
- `with dev=true`
https://github.com/user-attachments/assets/d0c44400-8302-4aa9-8f35-195a3d800b75
- `with prev and next page`
https://github.com/user-attachments/assets/1b04084d-e6ed-45f0-befd-fd19b76765be
</details>
<details>
</details>
- **This PR follows a …
> feat: lazy load discord groups page 

- constants/requests.ts
- controllers/onboardingExtension.ts
- controllers/requests.ts
- middlewares/skipAuthenticateForOnboardingExtension.ts
- middlewares/validators/onboardingExtensionRequest.ts
- middlewares/validators/requests.ts
- routes/requests.ts
- typeDefinitions/users.ts
- types/onboardingExtension.d.ts
- utils/requests.ts
Date: 20 Dec, 2024
---
- This PR only contains the changes related to feature. There is a separate PR #2306  for tests.
- This PR adds feature to create an onboarding extension request using POST /requests endpoint.
<details>
<summary>Working Videos</summary>
- When super-users make request for onboarding users and do not pass username
https://github.com/user-attachments/assets/fe7bdc50-ef81-4c57-89cb-a44cb6306eaf
- When super-users make request for onboarding users
https://github.com/user-attachments/assets/b8098f1c-7f1a-4c3a-85be-ebd794cc4083
- When non-onboarding users make a request
https://github.com/user-attachments/assets/27a0f7de-eed4-46d3-b12e-1f48548e8571
- When onboarding users make the request first time …
> feat: Add api to create onboarding extension request from discord server

- controllers/onboardingExtension.ts
- test/integration/onboardingExtension.test.ts
Date: 8 Jan, 2025
---
This PR fixes the error response when a user has a pending request and try to create another request.
<details>
</details>
<details>
</details>
> fix: send conflict response when user has a pending request

- middlewares/validators/requests.ts
- models/requests.ts
- test/integration/onboardingExtension.test.ts
- test/integration/requests.test.ts
- test/unit/models/requests.test.ts
Date: 2 Jan, 2025
---
This PR fixes GET /request endpoint by introducing ONBOARDING type in validator and fetching onboarding extension requests by requestedBy field under enabled feature flag.
<details>
</details>
<details>
</details>
> fix: Add support to fetch onboarding extension request

- models/discordactions.js
- test/integration/discordactions.test.js
- test/unit/models/discordactions.test.js
Date: 2 Jan, 2025
---
- The PR contains the fix and tests both. 
- This PR filters onboarding users and skip who have a valid approved extension request and then apply the `groupOnboarding31d+` role.
- The changes are not behind feature flag as the `/discord-actions/group-onboarding-31d-plus` api is invoked by cron job after every 30 minutes. I have not made the changes behind feature flag because there is not any user's control over feature flag to enable or disable it.
<details>
<summary>Working Videos</summary>
- Example when cron job run and apply `groupOnboarding31d+` role.
https://github.com/user-attachments/assets/3d6570f7-87b6-4848-9998-9f20638aa7ec
- Example when cron job run and skip the user who has valid approved extension request. …
> Fix: skip users having approved onboarding extension when applying groupOnboarding31d+ role

- controllers/onboardingExtension.ts
- controllers/requests.ts
- middlewares/validators/requests.ts
- test/integration/onboardingExtension.test.ts
- test/integration/requests.test.ts
- types/onboardingExtension.d.ts
Date: 29 Dec, 2024
---
This PR contains test and feature related to approval and rejection of onboarding extension request by super-users.
<details>
</details>
<details>
</details>
[Design doc](https://docs.google.com/document/d/17LAwNt_LijCR9HY5mHim5tGV70OkMkTETZEJ73n1q4w/edit?pli=1&tab=t.0#heading=h.w1nbw3goorza)
The Api contract has been updated. Here is the [PR](https://github.com/Real-Dev-Squad/website-api-contracts/pull/219)
> feat: Add api to approve and reject onboarding extension requests

- controllers/requests.ts
Date: `19th January, 2025`
Developer Name: [Achintya](@Achintya-Chatterjee )
---
- fix merge conflicts
fix the merge conflicts which happened because of the main branch was not in sync with develop
<details>
</details>
<details>
</details>
> fix : merge conflicts

- test/integration/progressesTasks.test.js
- test/integration/progressesUsers.test.js
- test/unit/models/progresses.test.js
- test/unit/utils/progresses.test.js
Date: 30 Dec 2024
Developer Name: @AnujChhikara
---
- closes #2319 
Addes tests for the pagination of the progresses API
<details>
</details>
<details>
</details>
Added tests for PR - #2325
> test : add tests for pagination of progresses api

- test/integration/onboardingExtension.test.ts
- test/unit/middlewares/requests.test.ts
- test/unit/services/onboardingExtension.test.ts
Date: 3 Dec, 2025
---
This PR adds test cases for the **PATCH /requests/:id** API for onboarding extension requests to ensure its correctness and reliability. The tests cover the following scenarios:
- Valid input for updating extension details.
- Invalid input handling (e.g., missing or incorrect fields).
- Authentication and authorization checks.
- Error handling for edge cases and unexpected failures.
These tests aim to improve the overall robustness and maintainability of the API.
<details>
</details>
Feature PR #2334
> feat: Add tests for PATCH /requests/:id API for onboarding extension requests

- controllers/requests.ts
- test/integration/requests.test.ts
Date: 25 Jan, 2025
Developer Name: @AnujChhikara
---
- Closes #2366 
- Fixed an issue where the Get Requests API fails with a 500 Internal Server Error when the `id` query parameter is provided (e.g., `?id=randomId`).
- Added test to validate the behavior of the `id` query parameter.
<details>
https://github.com/user-attachments/assets/0177a627-5efd-49c9-aa4b-57e1edb7cb9e
</details>
<details>
</details>
> Fix: Handle `id` query parameter in Get Requests API

- app.js
Date: 26 Jan, 2025
---
- Closes #2371 
This PR fixes the error handler middleware by adding support to send different error responses based on error types.
<details>
</details>
<details>
</details>
> Add support to send different error response from error handler middleware

- controllers/extensionRequests.js
- test/integration/extensionRequests.test.js
Date: 7 Feb 2025
Developer Name: @AnujChhikara 
---
- #2338 
- Added a default size=5 for the /extension-requests API when the size query parameter is not provided.
- Wrote a test to verify that the API returns exactly 5 extension requests by default.
<details>
- In the video, you can see that if the size query parameter is not provided, the response returns only five objects.
https://github.com/user-attachments/assets/ff075540-2b66-40ea-ae4c-aefb0e23e0d0
https://github.com/user-attachments/assets/24d5d1f6-1bb7-4e26-b41a-c64568a715b5
</details>
<details>
</details>
> fix: Set default size for GET /extension-requests API

- models/discordactions.js
- test/integration/tasks.test.js
- test/unit/models/discordactions.test.js
Date: 29 April, 2025
---
- Closes #2390 
- This PR fixes a bug where negligent tag was not being applied on users who had status other than ```ACTIVE``` and their task's status were not ```Completed```, ```VERIFIED``` or ```Done```. Now, the changes will apply negligent tag to all users who have status other than ```OOO``` and their task's status is not ```Completed```, ```VERIFIED``` or ```Done```.
- The changes are not behind feature flag because cron job executes this API and there is no user or any service involvement directly for now.
- The changes also fixes the existing test-cases.
<details>
<summary>Working Video</summary>
https://github.com/user-attachments/assets/ccb6c9c9-273c-42fc-af8b-7afc899eaf08 …
> Refactor negligent tagging logic to exclude only OOO users

- middlewares/shortCircuit.ts
- routes/discordactions.js
- test/integration/discordactions.test.js
Date: 31-May-2025
---
https://github.com/Real-Dev-Squad/todo-action-items/issues/269
Disabled Discord invite routes, as there is a bug which lets users generate discord links 
<details>
</details>
<details>
</details>
> Fix: Disable discord-actions/invite routes

- constants/bot.ts
- constants/constants.ts
- middlewares/authorizeBot.js
- services/botVerificationService.js
- test/config/test.js
- test/unit/middlewares/authorizeBot.test.js
- test/utils/generateBotToken.js
Date: 3 May 2025
Developer Name: Joy Gupta, @pankajjs 
---
- https://github.com/Real-Dev-Squad/website-backend/issues/2409
This PR contains an update to the logic of `verifyDiscordBot`. With these changes, the same middleware could authorize the requests from both the Discord service and the Discord slash.  
<details>
[screen-capture (1).webm](https://github.com/user-attachments/assets/405881f7-1a2d-4a39-9be6-b42cb8019d79)
</details>
> feat: add Discord service verification and token generation
