app.js, middlewares/index.js
- Reformatted app middlewares to prevent clutter in app.js file
=> [1] Reformatted app middlewares

config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, controllers/authController.js, controllers/healthController.js, middlewares/index.js, middlewares/passport.js, package-lock.json, package.json, routes/index.js, test/fixtures/auth/githubUserInfo.js, test/integration/authController.test.js
- Added a route to handle the callback from GitHub Auth
- Passport.js being used to handle the GitHub Oauth
- Added in integration tests
=> [2] Route to handle the callback from GitHub Auth

.gitignore, .mocharc.js, config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, controllers/authController.js, models/users.js, package-lock.json, test/integration/authController.test.js, utils/firestore.js
- Initialised firestore DB
- Storing user data on signup/login
=> [1] Initialised FireStore and storing user data in DB

config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, controllers/authController.js, middlewares/authenticate.js, models/users.js, package-lock.json, package.json, routes/index.js, services/authService.js, test/integration/authController.test.js
- Added functions to generate and validate JWT
- Added JWT token in the response cookie for `GET /auth/github/callback` route
- Haven't added tests for the added functions because of time constraints 😢
=> [2] Generate and validate JWT

controllers/membersController.js, server.js
=> Changed the db ref to import, instead of calling the function

README.md, config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, controllers/authController.js, middlewares/passport.js, services/authService.js, utils/firestore.js
- Added error boundary at passport initialization to prevent server start failures
- Modified README
=> [1] Modified README

CONTRIBUTING.md
- Added `CONTRIBUTING.md` containing contribution guidelines.
=> Added Contribution guidelines.

config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, controllers/authController.js, middlewares/authenticate.js, package.json, test/integration/authController.test.js, test/integration/healthController.test.js, test/unit/services/authService.test.js
- Fixed failing CI to validate the incoming PRs
- Added tests for JWT and authenticated routes
=> Fixed Failing CI

config/default.js, config/development.js, config/production.js, config/test.js, controllers/authController.js, test/integration/authController.test.js
- Added configurable cookie domain
=> [1] Added configurable cookie domain

config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js, middlewares/authenticate.js, package.json, services/authService.js
- Refresh JWT after expiry if the token init time is within the limits of the refreshTTL configured
- Minor typo fixes in package.json
=> [2] Refresh JWT after expiry

config/development.js, config/production.js, config/staging.js, config/test.js
- Reduced config redundancy
- Removed default config which was already defined in `default.js`
=> Reduced config redundancy

.eslintrc.js, config/production.js, config/staging.js, controllers/authController.js, middlewares/authenticate.js, models/users.js, package-lock.json, package.json, public/apidoc.json, services/authService.js, test/integration/authController.test.js, test/integration/healthController.test.js, test/integration/usersController.test.js, test/unit/services/authService.test.js
- Added linting
- Reformatted code
- Few files have been modified to have a consistent return statement
- The improper indents are removed
=> [1] Added linting and reformatted code

middlewares/contentTypeCheck.js, middlewares/index.js
- Added content-type check middleware as only `application/json` is supported by the API
=> [1] Added content type checks

middlewares/contentTypeCheck.js, test/unit/middlewares/contentTypeCheck.test.js
- Modified response code in content-type check middleware
- Added unit tests
=> Modified content-type check middleware and added tests

package-lock.json, package.json
- Added cross-env support for running in dev mode
- Added cross-env as a dev dependency
=> Added cross-env support for running in dev mode

middlewares/authenticate.js
- Modified object structure to pass correct userData to request object
- Currently, `user` object was being passed as a key in the response of `fetchUser` function. We just need the `user` object in `req.userData`
=> Modified object structure to pass correct userData to request object

CHANGELOG.md
=> [3] Added changelogs

CHANGELOG.md, CONTRIBUTING.md
- Modified contribution guidelines
=> [2] Modified contribution guidelines

CHANGELOG.md, CONTRIBUTING.md, README.md
- Modified README documentation
=> [1] Modified documentation for the API

config/default.js, config/development.js, config/staging.js, config/test.js, middlewares/index.js, test/unit/middlewares/security.test.js
- Added cors origin config
Related Issue: #56
=> Added cors origin config

.editorconfig, README.md
- Added support for .editorconfig file
- Most editors adopt to the configuration specified in the `.editorconfig` file. This will be useful for the developers who haven't configured limiting extensions in their IDE/editor. (https://editorconfig.org/)
- Updated README.md about API documentation.
=> Added support for .editorconfig file

package.json
Added cross-env support for test scripts so that they can work on Windows as well.
=> Added cross-env support for test scripts

.eslintrc.js, models/users.js, test/integration/healthController.test.js, test/integration/usersController.test.js, test/unit/middlewares/contentTypeCheck.test.js
Reverts Real-Dev-Squad/website-backend#68
=> Revert "Throw err from model functions instead of returning them"

controllers/membersController.js, models/members.js, routes/index.js, routes/members.js, utils/swaggerDefinition.js
Fixes #36 
- added GET `/members` API
- can be accessed publicly
Please review. Thank you!
=> added GET members API

controllers/usersController.js, middlewares/validators/user.js, models/users.js, routes/users.js
1) Added the PATCH users/self route. 
2) Added the username field to user Schema.
3) Deleted the PATCH users/:id route.
=> Addition of PATCH users/self route

routes/users.js, utils/swaggerDefinition.js
Added the swagger docs for PATCH users/self route. Fixes #77
=> Added the swagger docs for PATCH users/self route

routes/users.js, utils/swaggerDefinition.js
=> Swagger specifications for users routes

lib/fetch.js, package-lock.json, package.json
Optional parameters added to JSDoc
=> Optional parameters added to jsdoc of network call wrapper function

app.js, middlewares/responseHeaders.js
```
Cache-Control: no-store
```
=> Add response headers in API

local-test.js, package.json
=> Automation for checking local development environment is properly setup or not.

controllers/pullRequestsController.js, routes/pullrequests.js, services/githubService.js
Fetch oldest PRs from Real Dev Squad sorted by creation date and pagination
Closes #96
=> Fetch oldest Open PRs

routes/pullrequests.js
This is the solution for the issue #99 . Updated `/pullrequests/:username` to `/pullrequests/user/:username`
=> Updating API endpoint for fetching pullrequests

controllers/pullRequestsController.js
This is the solution for issue #102
=> Repository name added in response of pullrequests API

controllers/pullRequestsController.js, routes/pullrequests.js, services/githubService.js
Added a new route 'pullrequests/open' to show 10 latest open pull requests which are not merged yet. This is a solution for issue #103
=> New route added 'pullrequests/open'

local-test.js
Success message added on successful setup of backend. This is the solution for the issue #105
=> Success message added on successful setup of backend

README.md
Added instruction in Prerequisites for checking local environment setup.
=> Instruction in Prerequisites for local environment setup

.eslintrc.js, controllers/authController.js, controllers/membersController.js, controllers/pullRequestsController.js, controllers/roadmap-site/challengeController.js, controllers/usersController.js, middlewares/authenticate.js, middlewares/index.js, middlewares/passport.js, middlewares/validators/user.js, models/members.js, models/roadmap-site/challenges.js, models/roadmap-site/subscribe-challenge.js, models/users.js, server.js, services/authService.js, services/githubService.js, test/integration/authController.test.js, utils/fetch.js, utils/logger.js, utils/swaggerDefinition.js
- Made logger and config accessible globally to avoid importing it to every other file
=> Make `logger` and `config` accessible globally

middlewares/index.js, middlewares/responseHeaders.js
- Removed unneeded security headers from the library helmet
- Reference taken from: https://stackoverflow.com/a/60709460/8001821
=> Remove unneeded response headers

local-test.js, utils/swaggerDefinition.js
- Fixed missing config imports
=> Fixed missing config imports

controllers/pullRequestsController.js, routes/pullrequests.js, services/githubService.js
- Moved all the pull requests extracting code to a function, instead of doing same thing in 3 places, also there were differences in the items being returned in those 3 places.
Now they'll be unified
- Fixes #100 as well
=> refactored functions for pullrequests routes

test/integration/tasksController.test.js
- Added the tasks integration tests back in the project that were removed in https://github.com/Real-Dev-Squad/website-backend/pull/137
=> Added the tasks integration tests

README.md
- Sync main branch with develop
=> Sync main branch with develop

controllers/usersController.js, models/users.js, test/integration/usersController.test.js, test/utils/addUser.js
Fixes #155 
According to the API contract: https://github.com/Real-Dev-Squad/website-api-contracts/pull/23
=> returning `phone` and `email` only for users/self route when query `private` is true

models/tasks.js
=> adds fetchUserTasks model function back to fix broken contributions API

routes/users.js
removed the auth. from the routing /username.
=> Removed the auth. form the routing.

controllers/membersController.js
=> added response in case of no member found

.mocharc.js, models/users.js, scripts/tests/testIntegration.sh, scripts/tests/testUnit.sh, test/fixtures/user/user.js, test/integration/authController.test.js, test/integration/healthController.test.js, test/integration/tasksController.test.js, test/integration/usersController.test.js, test/unit/middlewares/contentTypeCheck.test.js, test/unit/middlewares/security.test.js, test/unit/services/authService.test.js, test/utils/addUser.js, test/utils/cleanDb.js
- Made every test exclusive by flushing the DB changes after every test
=> Made every test exclusive by flushing the DB changes after every test

test/fixtures/user/user.js, test/integration/membersController.test.js, test/integration/tasksController.test.js, test/integration/usersController.test.js
=> Adds tests for GET /members API

scripts/tests/testUnit.sh, test/unit/models/users.test.js, test/utils/cleanDb.js
- Added unit tests for addOrUpdate user model function
=> Added unit tests for addOrUpdate user model function

config/staging.js
- Added staging credentials in config
=> Added staging credentials in config

scripts/local-test.js
=> Added logs for processes being executed 

controllers/usersController.js, middlewares/authorizeOwner.js, mockdata/appOwners.js, routes/tasks.js, test/integration/tasksController.test.js
Authorize the user for post and update of the tasks #141
=> authorization middleware added

models/auctions.js
=> Saves bid and quantity as integer in db in `/auctions` routes

scripts/local-test.js
=> Checks if OAuth credentials are set up or not

utils/users.js
- Added safecheck for checking invalid participants array
- Fixes https://github.com/Real-Dev-Squad/website-backend/issues/274
=> Added safecheck for checking invalid participants array

constants/wallets.js, controllers/usersController.js, controllers/walletsController.js, models/users.js, models/wallets.js
Closes #284 
Tests ticket: #283
=> Create and initialize wallet if not found for user

controllers/auction.js
=> Checks if user has sufficient items to auction

test/unit/utils/users.test.js
Unit tests added for `getUsername` , `getUserId`, `getParticipantUsernames` and `getParticipantUserIds` functions in utils/users.js
=> Add unit tests for utils/users.js

middlewares/validators/user.js
=> Removed extra validation fields from user validator

scripts/validateSetup.js
=> Added emojis in validate-config messages

constants/tasks.js, middlewares/validators/tasks.js, test/integration/tasks.test.js, test/unit/utils/users.test.js
Closes #331 
Epoch type should be a number in tasks APIs
=> Fixed epoch datatype in tasks and tests #331

middlewares/authenticate.js, test/fixtures/user/user.js, test/integration/restricted.test.js, test/utils/addUser.js
=> Add middleware to check restricted user

controllers/pullRequests.js, routes/pullrequests.js, services/githubService.js
=> Adds pagination to `pullrequests` routes: `/stale` and `/open`

constants/users.js, docs/swaggerDefinition.js, middlewares/validators/user.js, test/fixtures/user/user.js, test/integration/users.test.js
@swarajpure @sumitd94 
I have added the Status property in User model.
Please review the PR!
=> Added status property in user object

.github/workflows/test.yml, CONTRIBUTING.md, package-lock.json, package.json
Closes #358, #361
~~Waiting on resolving the failing test for /tasks~~
=> Using firebase tools from local node_modules

controllers/members.js, models/members.js, test/fixtures/user/user.js, test/integration/members.test.js
Created new PR with new branch
Closes #262 
This PR should only be merged after successful run/merge of this PR #351
=> New members API for members page

CONTRIBUTING.md
Formatted the Contribute.MD
**And updated:**
with
- Make sure the server is not running.
=> Updating running test guide to not run server

constants/tasks.js, controllers/members.js
Updated the TASK_STATUS constant with a new value "UNASSIGNED: unAssigned".
ISSUE: Update task constants #366
@swarajpure 
@whyDontI
=> Added a TASK_STATUS  - unassigned to constants

controllers/challenge.js, models/challenges.js
if participants array contains more than 10 elements then code is using while loop to make a query with 10 elements of an array 
and iterate over the array till the end.
=> Populate participants/challenges

package-lock.json
Sync main to develop to auto-merge develop to main
=> Sync main to dev (Fix auto merge dev to main)

config/custom-environment-variables.js, config/default.js, config/development.js, config/staging.js, newrelic.js, package-lock.json, package.json, server.js
- Integrated Newrelic APM
- Have added Newrelic license key in staging and prod env with key name `INTEGRATIONS_NEWRELIC_LICENSEKEY`
=> Integrate newrelic apm

middlewares/responseHeaders.js
Read more about how CF caches here: https://developers.cloudflare.com/cache/about/cache-control
=> Add public to allow CF to cache /members

middlewares/responseHeaders.js
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
=> Set private cache for max-age=0 API calls

services/contributions.js
Closes this [issue](https://github.com/Real-Dev-Squad/website-members/issues/306)
=> Fix contributions API

controllers/arts.js, middlewares/validators/arts.js, models/arts.js, routes/arts.js, test/fixtures/arts/arts.js, test/integration/arts.test.js
Changes in Art API - 
Add integration test for add and self
- Only takes title(String), css(String) & price(Number) greater than 0
- Returns art ID in response
- Renamed `userArts` response to `arts`
- Removed cookie usage in the test
=> add art test & validator

middlewares/validators/user.js
=> add validation to check year of experience is positive or zero

controllers/tasks.js, models/tasks.js, test/integration/tasks.test.js
=> return tasks according to startedOn field

middlewares/validators/flag.js, routes/flag.js, test/fixtures/flag/flag.js, test/integration/flag.test.js, test/unit/models/flag.test.js
Added Unit tests and Integration test for flag/add endpoint.
Issue => closes #564
=> Feature flag/add tests validator

controllers/users.js, middlewares/validators/user.js, models/chaincodes.js, routes/users.js, test/fixtures/user/user.js, test/integration/users.test.js
=> identity -> profile and username -> userId

controllers/recruiters.js, models/recruiters.js, routes/members.js, test/fixtures/recruiter/recruiter.js, test/integration/members.test.js, test/integration/recruiters.test.js, test/unit/models/recruiters.test.js
Closes https://github.com/Real-Dev-Squad/website-backend/issues/472
Add on
- Added username while storing recruiter information
- Fixed member integration test for archiveMembers and moveTomembers
=> Added /members/intro API

models/auctions.js, nyc.config.js, scripts/tests/testIntegration.sh, scripts/tests/testUnit.sh, test/fixtures/currencies/currencies.js, test/integration/auction.test.js, test/unit/models/auctions.test.js
- Merge after #534
- Fixes https://github.com/Real-Dev-Squad/website-backend/issues/539
=> add unit tests for models/auction.js

test/fixtures/currencies/currencies.js, test/integration/auction.test.js, test/unit/models/wallet.test.js
=> add unit test for models/wallets.js

test/integration/auction.test.js
Resolves
- https://github.com/Real-Dev-Squad/website-backend/issues/591
=> fix auction test error 

constants/roles.js, middlewares/authorizeRoles.js, routes/members.js, routes/users.js, test/integration/authorizeRoles.test.js
=> refactor roles constant file

test/fixtures/currencies/currencies.js, test/integration/auction.test.js, test/unit/models/auctions.test.js, test/unit/models/wallet.test.js
Resolves
- https://github.com/Real-Dev-Squad/website-backend/issues/585
=> refactor currency fixture

controllers/users.js, test/integration/users.test.js, test/utils/checkChaincode.js
=> Chaincode in user

controllers/users.js, models/profileDiffs.js
=> Fix UpdateUser Function

controllers/users.js, models/profileDiffs.js
Description
- Handling undefined phone and email variable going in obfuscate function.
- throw error if something failed in obfuscation.
=> Fix obfuscate error

controllers/users.js, models/profileDiffs.js, utils/obfuscate.js
created a `obfuscate.js` in util and implemented in `controller/users.js` , `models/profileDiffs.js` 
closes #620
Enhancement feature
=> Added Obfuscate util for obfuscating Phone and email

models/profileDiffs.js
Description:
- Changed variable names so that we can fix lint issues.
=> Lint issues fixed

constants/users.js, controllers/members.js, routes/logs.js
* Removed ROLES constant from user.js
* Changed import paths for the same in depending files
fix: Passing correct role (superUser) to authorizeUser instead of undefined in logs route
Closes #644
=> Removed duplicate ROLES constant

test/utils/addUser.js
- #649 
* Add user in firestore without roles
* Update user's roles after adding the user in firestore
Closes #659 
Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/672
=> Implements expected behaviour while adding user in test util

test/integration/members.test.js
Rearranged beforeEach and afterEach blocks
Closes #680
=> Implements correct semantics in the test setup for members integration tests

.github/workflows/test.yml
- `.github/workflows/test.yml`
Removed the lines that run the test on push
The test will run every time you make changes to your branch. So, do not worry thinking if I make changes will the tests stop?
Currently, they run 2 times on (Pull_request and Push).
=> Modified test.yml to remove test workflow on Push

middlewares/validators/tasks.js, test/integration/tasks.test.js
RFC - #702 
- An additional test case has been added for this.
- updated the `joi` middleware for tasks for this issue.
=> Strict value acceptance for status in Task object

controllers/auth.js, test/integration/auth.test.js
#688 
The origin will get received as `state` through query at the backend and redirected to the origin
=> Redirect to origin after Sign In with GitHub

models/tasks.js
Added available status from a constant file, instead of using the hardcoded value
=> added available from constant file

controllers/users.js, middlewares/validators/user.js, models/users.js, test/fixtures/user/join.js
Fix model name for join section and key names for data.
closes : #749
=> fix model name and key names

middlewares/validators/tasks.js
This PR is related to https://github.com/Real-Dev-Squad/todo-action-items/issues/72 for building out task level feature
Issue: https://github.com/Real-Dev-Squad/website-backend/issues/743
=> tags feature

constants/users.js, controllers/tasks.js, middlewares/validators/user.js
Converted:
```js
const userStatusEnum = ["ooo", "idle", "active"];
```
To:
```js
const USER_STATUS = {
OOO: "ooo",
IDLE: "idle",
ACTIVE: "active",
};
```
And used it at the places where `userStatusEnum` was used
- https://github.com/Real-Dev-Squad/website-backend/issues/754
- https://github.com/Real-Dev-Squad/website-backend/issues/766
=> Added object enum for user status.

config/default.js, config/development.js, config/production.js, config/staging.js, config/test.js
Solves https://github.com/Real-Dev-Squad/website-backend/issues/756
Changed the Regex from `/(\.realdevsquad\.com$)|(localhost)/` to `/(https:\/\/([a-zA-Z0-9-_]+\.)?realdevsquad\.com$)|(localhost)/` in Allowed origins
=> fix CORS error

controllers/users.js, models/users.js, routes/users.js
- added an endpoint to get skills of the users
=> added get endpoint for getting user skills

controllers/users.js, routes/users.js, test/integration/users.test.js
The Backend wasn't sending the status code
This pr sends in the status code to tackle problems in frontend
Change POST request to PUT request as we are creating a single resource.
change status code from 200 to 201 for resource creation.
=> add status code in response of join section and change post to put request

controllers/levels.js, middlewares/validators/levels.js, models/levels.js, routes/index.js, routes/levels.js
created apis for creating, removing generic levels for items
=> Generic model level

constants/tags.js, controllers/tags.js, middlewares/validators/tags.js, models/tags.js, routes/index.js, routes/tags.js
Added generic models to create, add and remove tags
=> Generic model tags

controllers/levels.js, controllers/tags.js, middlewares/validators/levels.js, models/levels.js, models/users.js
- we have changed the ItemModel values to camelCase, this will creates issues in two APIs: `/users/suggestedUsers/:skillId` and `/users/:id/skills`, 
- This PR will fix that issue
=> replaced itemModel values to camelCase

controllers/tasks.js, models/tasks.js, test/integration/tasks.test.js, utils/users.js
- enhances the currently available task assignment endpoint based on the new requirements
=> added task-endpoint enhancement

constants/items.js, controllers/items.js, middlewares/validators/items.js, middlewares/validators/levels.js, models/items.js, models/levels.js, models/tasks.js, models/users.js, routes/index.js, routes/items.js
APIs for adding tags, and removing tags to & from various items. Also fetching items based on tag types, tags and items
=> Generic model items

middlewares/validators/levels.js, models/items.js, models/levels.js, models/tasks.js
- changes level and name in the `item` collection
- changes level to value in the `level` collection
=> changed the level name and value

controllers/userStatus.js, models/userStatus.js, routes/index.js, routes/userStatus.js, test/integration/userStatus.test.js, utils/userStatus.js
Closes https://github.com/Real-Dev-Squad/website-backend/issues/857
=> Adds new routes & tests for users/status Endpoint

controllers/userStatus.js, models/userStatus.js, routes/index.js, routes/userStatus.js, test/fixtures/userStatus/userStatus.js, test/integration/userStatus.test.js, utils/userStatus.js
This PR fixes a bug that earlier we were not allowing to create new user status with a partial object (i.e only if current status or monthly hours was present). Now we have removed this condition. This PR once merged will allow Users to create a new User Status Object with partial data (i.e either the key current status or monthly hours being present). 
This is a stacked PR and should be merged after https://github.com/Real-Dev-Squad/website-backend/pull/858
=> Status API patch refactor

controllers/userStatus.js, models/userStatus.js
- #855 
The users were sorted alphabetically earlier, but now, they will be sorted on the basis of how long they have been IDLE/ACTIVE/OOO. Read more https://github.com/Real-Dev-Squad/website-status/issues/336
=> Sort users based on how long hey have had a particular state from

CONTRIBUTING.md
Updated GitHub login link in docs for staging environment
Link for the issue :-
https://github.com/Real-Dev-Squad/website-backend/issues/838
=> Updated GitHub login link

controllers/userStatus.js, models/userStatus.js, test/fixtures/user/user.js, test/integration/userStatus.test.js
The issue:
In the frontend we need data about user profile image and Name so, in the data that is returned from `/users/status` API, 
```js
{
"currentStatus": {
"message": String,
"until": Timestamp,
"updatedAt": Timestamp,
"state": String,
"from": Timestamp
},
"monthlyHours": {
"updatedAt": Timestamp,
"committed": Integer
}
}
```
we will also return 
```js
{"currentStatus": {
"message": String,
"until": Timestamp,
"updatedAt": Timestamp,
"state": String,
"from": Timestamp
},
"monthlyHours": {
"updatedAt": Timestamp,
"committed": Integer
},
"full_name": String,
"picture": {
"url": String,
"publicId": String
}
}
```
- Added picture field in users fixture because we were getting it in the Prod but there was no test for it.
=> Add user profile w.r.t the userID

controllers/userStatus.js
To get the user details of a user on clicking a user from idle user page, the username is required
=> return username on GET users/status

middlewares/validators/userStatus.js, test/fixtures/userStatus/userStatus.js, test/integration/userStatus.test.js
=> reason not mandatory when user is OOO for less than 3 days 

middlewares/validators/userStatus.js, models/userStatus.js, routes/userStatus.js, test/fixtures/userStatus/userStatus.js, test/integration/userStatus.test.js, utils/userStatus.js
- Adds validation check for `from` and `until` field not lying before current date
- Adds validation check for `until` field falls after or on `from` field in case of OOO. 
- Refactor as per the code comment in the PR #884
=> future status refactor

controllers/userStatus.js, test/fixtures/user/user.js, test/integration/userStatus.test.js
=> Archive role check for queried Users State

controllers/users.js, test/fixtures/user/join.js, test/integration/users.test.js
Hello @RitikJaiswal75 , I have fixed  the changes regarding the issue #850 .
closes: #850 
Now if the user makes put request at the route users/self/intro at first the data is created and the message is returned ( as in image below ).
And when the user has one join data present in the database it returns the message ( as in image below ).
Please look into it and tell me if something needs to be rectified or updated.
Thanks!
=> Fixed join section multiple data creation issue

config/custom-environment-variables.js, config/default.js, config/development.js, config/test.js, constants/bot.js, controllers/discord.js, middlewares/authorizeBot.js, middlewares/validators/discord.js, middlewares/validators/user.js, models/discord.js, routes/discord.js, routes/index.js, services/botVerificationService.js, test/fixtures/discord/discord.js, test/integration/discord.test.js, test/unit/middlewares/authorizeBot.test.js, test/unit/models/discord.test.js, test/utils/generateBotToken.js
Resolves #912 
- Made an API named as `/discord` which performs the action of adding the data coming from the `/verify` command 
- The server to server connection is secured by a JWT verification  from the headers
https://github.com/Real-Dev-Squad/website-api-contracts/pull/105/
https://github.com/Real-Dev-Squad/website-data-models/pull/19
=> Discord Bot API

controllers/auth.js, models/users.js
What does this PR do: 
- adds redirection to the new-signup page of my site in case the user has incomplete details
=> added integration for new sign up flow in backend

constants/firebase.js, controllers/users.js, models/users.js, utils/users.js, yarn.lock
Reverts Real-Dev-Squad/website-backend#1027
=> Revert "develop to main sync"

utils/cache.js
=> `/tasks` api empty string response issue

controllers/users.js, middlewares/validators/user.js, models/users.js, test/integration/usersFilter.test.js
=> Remove Test Skip and Handled no User found 

controllers/issues.js, controllers/tasks.js, controllers/users.js, middlewares/validators/tasks.js, middlewares/validators/user.js, models/tasks.js, models/users.js, routes/index.js, routes/issues.js, services/githubService.js, services/issuesService.js, test/fixtures/standup/standup.js, test/fixtures/user/user.js, test/integration/auth.test.js, test/integration/standup.test.js, test/integration/usersFilter.test.js, test/unit/models/users.test.js, test/unit/services/githubService.test.js, utils/cache.js, utils/users.js, yarn.lock
> **Warning** 
> ### DO NOT MERGE
> Please make sure all the 3 steps before this has been completed here:
> - [x] https://github.com/Real-Dev-Squad/todo-action-items/issues/148
=> Develop to Main

controllers/users.js, models/users.js
Fixes: #1026
* rename variable `filterdUsersWithDetails` with `users` and `filteredUsernames` with `usernames`
=> fix: rename variables under users controller

config/custom-environment-variables.js, config/default.js, config/test.js, controllers/discordactions.js, middlewares/validators/discordactions.js, middlewares/verifydiscord.js, models/discordactions.js, routes/discordactions.js, routes/index.js, test/fixtures/discordactions/discordactions.js, test/unit/models/discordactions.test.js
This PR contains the code for the features of [create-group-roles](https://github.com/Real-Dev-Squad/website-dashboard/issues/340) and [add-group-role](https://github.com/Real-Dev-Squad/website-dashboard/issues/341) and [isDiscordVerified](https://github.com/Real-Dev-Squad/website-backend/issues/1062) for `website dashboard` integration.
=> Discord action roles

middlewares/validators/tasks.js, services/contributions.js, test/integration/tasks.test.js
=> add isCollapsed field

constants/progresses.js, controllers/progresses.js, middlewares/validators/progresses.js, models/progresses.js, routes/index.js, routes/progresses.js, utils/progresses.js
These three API endpoints are related to tracking progress for a particular user or task. Here's a brief description of each:
1. `POST /progresses`: This endpoint allows us to create a new progress entry. 
2. `GET /progresses`: This endpoint allows you to retrieve progress entries based on the provided parameters. 
3. `GET /progresses/range`: This endpoint allows you to retrieve progress records for a particular user or task within the specified date range.
The Issue ticket can be found [here](https://github.com/Real-Dev-Squad/website-backend/issues/1076)
The Data Model for these APIs can be found  [here](https://github.com/Real-Dev-Squad/website-data-models/tree/main/progress)
The API Contract can be found [here](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/progress) …
=> Add progress tracking API endpoints

constants/progresses.js, controllers/progresses.js, test/integration/progressesTasks.test.js, test/integration/progressesUsers.test.js, utils/progresses.js
This pull request follows a Test-Driven Development (TDD) approach to remove the test skips for the progresses API. Additionally, this PR introduces the use of the INTERNAL_SERVER_ERROR_MESSAGE constant. This constant allows for consistent error handling by providing appropriate 500 error responses with relevant messages, while avoiding the exposure of exact error details.
The Parent ticket can be found [here](https://github.com/Real-Dev-Squad/website-backend/issues/1076)
=> Remove the test skips for progresses API (TDD approach)

middlewares/verifydiscord.js
Add a condition in middleware to block archived users to use discord features
closes #1108 
Tests will be coming in future PRs, Here is the issue ticket for the same: #1110
=> modify condition to block archived users from using discord actions

controllers/tasks.js, test/integration/tasks.test.js
Issue(#1085)
This code checks if a task has an assignee
then you search for it in user db
if the user does not exist you return a 404 saying user dosen't exist
=> fixed the bug for assignee patch request

config/test.js, controllers/external-accounts.js, routes/external-accounts.js, services/discordService.js, test/fixtures/discordResponse/discord-response.js, test/integration/external-accounts.test.js
Consume a pre-created function and create an endpoint to sync discord users and add their joined at date.
lines for controller written by me are covered
- #1155
=> add an endpoint to sync discord users

models/users.js, services/discordService.js, test/fixtures/user/inDiscord.js, test/unit/services/discordService.test.js
This PR is part of a big PR to create an endpoint to add an in_discord role as false for all users. This PR just creates and tests the service we are still pending on the route creation.
Test Coverage:
Lines written by me: 34-47
=> add a service to set in discord role as false for all users

models/users.js, test/unit/models/users.test.js
Sync dev to main
Developer name: ritik
prs going in:
- #1167 
Verified in staging with a new user:
=> sync dev to main

test/unit/middlewares/arts-validator.test.js
- Implemented comprehensive test coverage for the Arts Validator Middleware, ensuring its effectiveness in validating requests passed to create arts.
- Utilized the Chai testing framework and Sinon for mocking dependencies, facilitating robust and accurate test cases.
- Verified the correctness of the middleware by writing unit tests for different scenarios, including valid and invalid requests.
- Improved Code Quality: By adding tests for the Arts Validator Middleware, we enhance the overall code quality and reduce the risk of introducing regressions.
- Enhanced Reliability: Thorough test coverage helps to identify and fix potential bugs or issues related to the art creation process.
- Better Maintainability: The presence of tests ensures that future modifications or updates to the Arts …
=> Adding Tests for Arts Validator Middleware

test/unit/models/users.test.js
This pull request focuses on enhancing the reliability and correctness of the Applicant model by adding comprehensive tests for its setter and getter functions. The tests, written using the Mocha testing framework, ensure proper data assignment, validation, and retrieval. Additionally, the Firebase Emulator is utilized to simulate the database environment, enabling thorough testing of the model's interaction with the database.
- Write Mocha tests for the setter functions of the Applicant model:
- Test each setter function to ensure accurate data assignment and proper validation.
- Verify that the model handles various data scenarios correctly and produces the expected results.
- Write Mocha tests for the getter functions of the Applicant model:
- Test the behavior of each getter function …
=> Add Mocha Tests for Applicants Model Setter and Getter Functions with Firebase Emulator

services/discordService.js, test/unit/services/discordService.test.js
This pull request adds comprehensive tests for the `getDiscordMembers` function, which is responsible for retrieving all the members from the Real Dev Squad's Discord server. The purpose of these tests is to ensure the accuracy and reliability of the function, enhancing the overall quality of the codebase.
- Added test cases to cover various scenarios, including different member counts, roles, and edge cases.
- Utilized mocking techniques to isolate the function under test and simulate different server configurations and responses.
- Implemented both positive and negative test cases to verify expected behavior and handle potential errors.
1. Tested the handling of server errors, such as rate limits or connection issues.
2. Checked if the function correctly filters members based on …
=> Add Tests and refactor `getDiscordMembers` Function

test/unit/middlewares/auctions-validator.test.js
=> add tests for auctions validator

test/unit/middlewares/challenges-validator.test.js
=> add tests for challenges validator

test/unit/middlewares/discordactions-validators.test.js
=> add tests for discord actions validator

test/unit/middlewares/external-accounts-validator.test.js
=> add tests for external accounts validator middleware

middlewares/validators/user.js, models/users.js, test/fixtures/user/user.js, test/integration/usersFilter.test.js
* Returns users with archived role if passed in query
Fixing: #1039
=> feat: return archived users if asked for using user/search endpoint

controllers/userDeviceInfo.js, middlewares/validators/userDeviceInfo.js, models/userDeviceInfo.js, routes/index.js, routes/userDeviceInfo.js, test/fixtures/userDeviceInfo/userDeviceInfo.js, test/integration/userDeviceInfo.js, test/unit/models/userDeviceInfo.test.js
Closes #941 
POST API call which will take user-id and the device name in the body and stores them in DB.
**_Response_**
=> Added user device info in db for mobile auth

constants/users.js, controllers/users.js, models/users.js, services/dataAccessLayer.js, test/fixtures/user/user.js, test/integration/users.test.js, test/unit/services/dataAccessLayer.test.js
Date: 12.07.2023
Developer Name: @mailmesriza98 
PR Number(s):- https://github.com/Real-Dev-Squad/website-backend/pull/1222
Issue Ticket Number:- https://github.com/Real-Dev-Squad/website-backend/issues/1271
Yes
No
No
No
None
Yes
=> Dev to Main sync

utils/cache.js
- Currently, when we update the task from the status site it takes 2 minute to reflect due to cache so to overcome the issue we have to decrease the cache time
**Follow-up PR**
=> Changed cache time

config/default.js, config/staging.js, config/test.js, constants/bot.js, middlewares/authorizeBot.js, routes/external-accounts.js, services/botVerificationService.js, test/unit/middlewares/authorizeBot.test.js, test/utils/generateBotToken.js
- https://github.com/Real-Dev-Squad/website-backend/issues/1288
This pull request addresses the GitHub issue #1286 : "Create Middleware for Verifying Requests from Cron Job Handler and Use RSA Keys for JWT Verification (RS256)." The changes proposed in this pull request aim to implement the necessary middleware to verify incoming requests from our own cron job handler using RSA keys for secure JWT verification with the RS256 algorithm.
1. Added a new middleware module that intercepts incoming requests and performs sender verification.
2. Implemented RSA key generation and management to enable JWT verification with the RS256 algorithm.
3. Developed comprehensive unit tests to ensure the correctness and robustness of the middleware and JWT verification process.
- The middleware validates …
=> Feature: Create a middleware to authorize cron jobs

controllers/users.js, services/dataAccessLayer.js, test/unit/services/dataAccessLayer.test.js
closes https://github.com/Real-Dev-Squad/website-backend/issues/1239
=> Refactor GET /users/search route to start consuming service/dataAccessLayer.js

controllers/tasks.js, middlewares/validators/tasks.js, test/integration/tasks.test.js
Fixes: 
#1216  
* Adds validation to percentCompleted param to accept value between 0 to 100
* Adds integration tests for the above case
=> feat: validate percentComplete value to be from 0 to 100

test/integration/taskBasedStatusUpdate.test.js, test/unit/middlewares/userStatusValidator.js, test/unit/utils/userStatusValidator.test.js
Removes the test skips for the task based status update changes
=> removes the skip from the tests

constants/errorMessages.js, controllers/auth.js, middlewares/validators/qrCodeAuth.js, models/levels.js, models/qrCodeAuth.js, routes/auth.js, test/integration/qrCodeAuth.test.js, test/unit/middlewares/qrCodeAuthValidator.test.js, test/unit/models/qrCodeAuth.test.js
Closes #1011 and closes 3/3 for #1176 
GET API call to retrieve the QR-code-auth document to retrieveEndpoint: GET /auth/qr-code-auth
**_Response_**
**_Error 404_**
**_Error 400_**
=> `GET` route for fetching user device info for qr-code mobile auth

nyc.config.js, scripts/tests/testUnit.sh
Remove dist folder from coverage
=> exclude dist folder from coverage report

models/userStatus.js, test/integration/taskBasedStatusUpdate.test.js, test/unit/models/taskBasedStatusUpdate.test.js
The Idle Users Sync API returns metric. As per Ankush suggestion I have modified some of the fields. 
This PR doesn't need any testing stats.
=> Rename fields as per Ankush Suggestion

routes/users.js, test/integration/users.test.js
=> change http method and also the name of endpoint

controllers/tasks.js, test/integration/tasks.test.js
**Before Changes**
**After Changes**
=> Fix empty search term case in filter task

controllers/tasksRequests.js, models/taskRequests.js, routes/taskRequests.js, test/integration/taskRequests.test.js
closes #1273 
The following PR contains the tests for the model which have been separated from this PR.
#1300 
&nbsp;<details><summary>Show Screenshot</summary>![Screenshot from 2023-07-18 20-42-08](https://github.com/Real-Dev-Squad/website-backend/assets/26207583/f4ac21f4-63fa-4b34-bbf3-66b56aa7e3b2)</details>
=> feat: Add fetchTaskRequestById

controllers/events.js, middlewares/validators/events.js, models/events.js, routes/events.js, test/unit/models/events.test.js
=> [Live-Site] feat: added api to kickout peer

controllers/discordactions.js, models/discordactions.js, models/users.js, services/dataAccessLayer.js, test/fixtures/discordactions/discordactions.js, test/integration/discord.test.js, test/integration/discordactions.test.js, test/unit/models/discordactions.test.js, test/unit/models/users.test.js, test/unit/services/dataAccessLayer.test.js
This pull request adds group creator details, including first name, last name, and profile picture, which will be displayed in the dashboard UI. Additionally, a new field called "count" is introduced to indicate the number of members in the group. These changes are expected to enhance the dashboard user interface and provide more comprehensive information.
Fixes: #1382 
``` 
{
"message": "Roles fetched successfully!",
"groups": [
{
"id": "15PPEWydQ84YlK6MlK6z",
"date": {
"_seconds": 1689451955,
"_nanoseconds": 807000000
},
"createdBy": "CvUmCEm6vB9pczLBli0z",
"rolename": "group-Too-Much-Truth",
"roleid": "1129868137827938324"
}
]
}
```
```
{
"message": "Roles fetched successfully!",
"groups": [
{
"id": "mExFFXEJo2YL8XBbdYJ1",
"date": {
"_seconds": 1689838197,
"_nanoseconds": 139000000
}, …
```
=> Added member count and creator details in the GET discord-actions/groups API.

middlewares/validators/user.js, test/integration/users.test.js, test/unit/middlewares/user-validator.test.js
Reverts Real-Dev-Squad/website-backend#1384
=> Revert "Fix/username validator"

controllers/members.js, test/integration/members.test.js
**Previous test case:**
**Test cases and coverage:**
=> Fix: Test for internal server error for /archivedUsers

controllers/auth.js, middlewares/validators/qrCodeAuth.js, models/qrCodeAuth.js, routes/auth.js, test/unit/middlewares/qrCodeAuthValidator.test.js, test/unit/models/qrCodeAuth.test.js, utils/generateUniqueToken.js
=> Verify status validation1

middlewares/validators/staging.js
fix not being able to assign archived roles in staging
=> fix the staging for archived users

controllers/users.js, models/users.js, routes/users.js, test/integration/users.test.js, test/unit/models/users.test.js
This is a follow up and a clean up PR to the PR: #1227
=> removing one time script to remove tokens

controllers/tasks.js, middlewares/validators/tasks.js, models/tasks.js, test/integration/tasks.test.js, test/unit/middlewares/tasks-validator.test.js, test/unit/models/tasks.test.js, test/unit/utils/transformQuery.test.js, utils/tasks.js
Closes #1430: Create API for Filtering Tasks Based on Assignee and Task Title
This pull request implements the requested feature to filter tasks based on assignee and task title. Users can now efficiently find tasks assigned to a specific team member or with a specific title, improving the functionality and usability of the task management system.
- Implemented the `/tasks` API endpoint with support for filtering by `assignee` and `title` query parameters.
- Added logic to filter tasks based on the provided parameters.
- Implemented proper error handling for invalid or missing parameters.
- Returned a JSON response containing the filtered tasks.
Currently, the feature is behind a feature flag. To enable the feature, set the `dev` query parameter to `true`.
The API endpoint can be accessed …
=> FEATURE: Filter task based assignee and task title

middlewares/validators/user.js, test/integration/users.test.js, test/unit/middlewares/user-validator.test.js
#1352 
While editing a profile one can enter special characters @ in the social id, Make changes to the API such that it throws an error on an invalid social id.
1. Added the validation such that a social id that fails the acceptance criteria cannot be added to the database.
2. Show appropriate error and error messages if the Acceptance criteria fail.
**After:**
**Unit Test**
=> Social id should not contain special character @

controllers/events.js, middlewares/validators/events.js, routes/events.js, test/fixtures/user/user.js, test/integration/events.test.js, test/unit/services/users.test.js
This PR contains the changes that were needed for onboarding flow change in `live-site`.
=> [Live-Site] feat: join changes in events in live-site

controllers/userStatus.js, models/discordactions.js, models/userStatus.js, routes/userStatus.js
=> group-idle role on idle members

models/discordactions.js, models/userStatus.js
=> Tests fixed in develop

models/discordactions.js, models/userStatus.js
Changes going:
- Detailed report for PUT request /discord-actions/group-idle
=> Dev to main

controllers/discordactions.js, models/discordactions.js, routes/discordactions.js, test/integration/discordactions.test.js
- https://github.com/Real-Dev-Squad/website-dashboard/issues/479
Api returns the group roleId of groups user is part of
=> created api for user group roles id and added integration test

models/tasks.js, test/integration/tasks.test.js, test/unit/models/tasks.test.js
We've added the ability to fetch overdue tasks based on the assignee, making it easier than ever to stay on top of your team's responsibilities.
**Create the indexes in Firestore:**
We need to add the following indexes to our Firebase database
<details>
<summary>Steps to Add Indexes</summary>
1. Open the **Firebase console**.
2. Navigate to the **database section**.
3. Click on the **"Indexes"** tab.
4. Click on the **"Add Index"** button.
</details>
- https://console.firebase.google.com/v1/r/project/ **[PROJECT NAME]** /firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC1lZjZlZi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QARoMCghfX25hbWVfXxAB
- …
=> FEATURE: Fetch overdue task based on assignee

models/tasks.js
=> FIX : task not return based on assignee

controllers/discordactions.js, controllers/users.js, models/users.js, routes/users.js, services/users.js, test/fixtures/user/user.js, test/integration/discordactions.test.js, test/integration/users.test.js
- added `nickname_synced` field
=> UPDATE: nickname_synced field added

services/users.js
Created a recursive function which updates/adds `nickname_synced` field for users as a batch of 500 for large number of users.
=> adding/updating field for more than 500 users in DB

controllers/users.js, routes/users.js, services/users.js
* REFACTOR: Remove nickname_synced field
* CHORE:remove non-useful test
* REFACTOR
* move the patch remove nickname synced api above the activated api for userId
* FIX: delete document field
* CHORES: lint fix
---------
=> Refactor/nickname synced field (#1551)

controllers/auth.js, test/integration/auth.test.js, test/utils/github.js
**ticket**: https://github.com/Real-Dev-Squad/website-backend/issues/1559
updated backend according to the mobile-app signIn with github flow.
**Test Report**
=> Req: Update SignIn with Mobile to Handle Query Parameters and Redirect to Mobile App

controllers/users.js, models/users.js, test/integration/usersFilter.test.js, test/unit/models/users.test.js
To improve our user management, we need to refactor the code to return only those users who are in our Discord server .
=> Refactor to Retrieve Users in Discord only

config/custom-environment-variables.js, config/default.js, config/test.js
Closes #1567 
In this PR I have fixed API key name to all capitalize.
=> fix: API key name to all capital case

controllers/tasks.js, test/integration/tasks.test.js
Solves #1556 
This PR helps in adding a `startedOn` date the moment a task is assigned for the first time
controllers/tasks.js : Added an if block inside the block where we check if we got assignee in the request body.
Before:
After:
=> add the fix for the invalid date bug and test cases

controllers/events.js, middlewares/validators/events.js, test/integration/events.test.js
=> [Live-Site] feat: join existing events if present

middlewares/validators/progresses.js, test/integration/progressesTasks.test.js, utils/progresses.js
Date:02-10-23
Developer Name: Shubham Sharma
PR Number(s):-
Issue Ticket Number:- https://github.com/Real-Dev-Squad/website-backend/issues/1569
Yes
No
No
No
Any special instructions for the deployment
No
No
Also attach their screenshots.
No
=> Added query parameter orderBy in progress API

middlewares/validators/progresses.js, test/integration/progressesTasks.test.js, utils/progresses.js
Reverts Real-Dev-Squad/website-backend#1578
Giving error on staging wbv
=> Revert "Added query parameter orderBy in progress API"

controllers/users.js, middlewares/validators/user.js, test/integration/users.test.js
Issue
-----
-   [Update Query Parameter Format in API Endpoint #1449](https://github.com/Real-Dev-Squad/website-backend/issues/1449)
Description
-----------
-   Update Query Parameter Format in API Endpoint.
-   [x]  Yes
-   [ ]  No
-   [ ]  Yes
-   [x]  No
-   [ ]  Yes
-   [x]  No
-   [ ]  Yes
-   [x]  No
-   [x]  Yes
-   [ ]  No
None
Test stats
----------
-   Before :\
-   After :\
Working Proof
----------------
=>  update query paramter format from query to q for users endpoint

controllers/extensionRequests.js, models/logs.js, test/fixtures/logs/extensionRequests.js, test/integration/extensionRequests.test.js, test/integration/multilpleExtensionRequest.test.js, test/unit/models/logs.test.js, utils/users.js
- https://github.com/Real-Dev-Squad/website-backend/issues/1515
Please make sure that the following composite index is already created: 
> [Created for staging ](https://github.com/Real-Dev-Squad/website-backend/issues/1614)
- https://github.com/Real-Dev-Squad/website-dashboard/pull/573
- https://github.com/Real-Dev-Squad/website-my/pull/503
- https://docs.google.com/document/d/1sf-BAs7C6wmfjRVS-82X492hcb_7jAfIM-7pWtizuXE/edit
Run `yarn test-unit` and there you can see test case running.
=> Fetch extension request logs of a given taskID for super user

controllers/tasksRequests.js, middlewares/taskRequests.js, models/taskRequests.js, test/integration/taskRequests.test.js, test/unit/models/tasks-request.js
- #1583 
- https://github.com/Real-Dev-Squad/website-status/issues/920
Replace the existing approve task request model function with a new one which will either create or update a task based on the request type.
code change lines - 131 to 229
=> Adds a new model function to approve task requests

middlewares/taskRequests.js, test/integration/taskRequests.test.js
- Removes validation where task request for user was not allowed to be approved when their user status was ACTIVE.
- Removes validation for user status.
Date: 24 Oct 2023
Issue Ticket Number:- - #1583 
Yes
No
Yes
No
No
Any special instructions for the deployment
Test code coverage:
=> Removes validation for user status in task requests

controllers/tasksRequests.js, test/integration/taskRequests.test.js
When the task request is approved successfully and task is assigned to the user. User status state is updated to ACTIVE.
Date: 27 Oct 2023
Issue Ticket Number:- - #1583 
Yes
No
Yes
No
No
N/A
Test code coverage:
=> Updates user status on task update

controllers/tasks.js, test/integration/tasks.test.js
Reverts Real-Dev-Squad/website-backend#1644
=> Revert "Replace 'COMPLETED' with 'DONE' in Backend from 'updateTaskStatus' Function"

controllers/events.js, models/events.js, test/fixtures/events/peers.js, test/integration/events.test.js, test/unit/models/events.test.js
Date: 31-10-2023
Developer Name: Satyam Bajpai
PR Number(s):- #1649
Issue Ticket Number:- #1648
Any special instructions for the deployment (none)
Logs response snapshot
> model unit tests
> controller integration tests
=> feat: changes for event kickout logs

models/tasks.js, test/fixtures/tasks/tasks.js, test/unit/models/tasks.test.js
**Description:** 
Fix "Cannot read properties of undefined" error in "tasks.js" to ensure the correct behavior
Developer Name: @sahsisunny 
PR Number(s):- 
- #1663
- #1664 
Yes
No
No
No
No
Any special instructions for the deployment
No
List of PRs going in this Sync.
- #1663
Also attach their screenshots.
**Test**
**Test Coverage**
=> fix: type error in task models

controllers/users.js, test/fixtures/tasks/tasks.js
Developer Name: @sahsisunny 
PR Number(s):-
- #1666
Yes
No
No
No
No
Any special instructions for the deployment
No
Description : 
In this PR we check if the task has an assignee or not. If the task has an assignee then get their user data for returning overdue users.
Test Coverage
Also attach their screenshots.
=> fix: skip if task assignee have undefined

.github/pull_request_template.md
This PR adds a template for all the PRs which are raised in backend
This is how the template will look like
=> template for all the pull requests raised in backend

services/tasks.js, test/unit/services/tasks.test.js
Date: 18-11-2023
Developer Name: @shubhamsigdar1 
----
- ### **Please refer this pr also while reviewing**: https://github.com/Real-Dev-Squad/website-backend/pull/1692
- Added service file which is used to perform batch operation and update all the task status COMPLETED to DONE
- Design Doc: https://docs.google.com/document/d/14reXnCwvnaQcjwKgfZweSCXdvLxjjdAA7Tr_DZOqJ84/edit?usp=sharing
- Written Test
**services/tasks.js**
https://github.com/Real-Dev-Squad/website-backend/assets/107163260/2300aa8b-b8c1-4b5c-90ca-f3447e02cf2f
=> Batch operation to Migrate status COMPLETED to DONE in tasks model

controllers/tasks.js, test/integration/tasks.test.js
Pr depend on- https://github.com/Real-Dev-Squad/website-my/issues/521
- remove COMPLETED with 'DONE' from 'updateTaskStatus' function
- Now user change status to DONE then all the condition before applied to COMPLETED will replace by DONE
- Under feature flag changes PR which merged before: https://github.com/Real-Dev-Squad/website-backend/pull/1657
**Before Changes**
https://github.com/Real-Dev-Squad/website-my/assets/107163260/31c3d80a-d25e-499c-bc7c-52f0dfeac180
**After Changes**
https://github.com/Real-Dev-Squad/website-my/assets/107163260/e1105d30-b94b-41a7-8eae-6add5afeda89
=> Remove feature flag: replace 'COMPLETED' with 'DONE' from 'updateTaskStatus' function

controllers/tasks.js, models/tasks.js, routes/tasks.js, services/tasks.js, test/integration/tasks.test.js, test/unit/models/tasks.test.js, test/unit/services/tasks.test.js
Reverts Real-Dev-Squad/website-backend#1705
The script is not yet run, so its required
=> Revert "Remove code- One-Time Script to Migrate Status from "COMPLETED" to "DONE" in taskModel Database"

test/integration/tasks.test.js
Date: 24-11-23
----
- #1712
Fix 1715's breaking tests
Added cleanup code to remove data from DB, in task/migrations test to add createdAt and updatedAt
=> Added cleanup code for fixing tests in tasks/migrations to add createdAt and updatedAt

services/tasks.js, test/integration/tasks.test.js
Date: 24-11-23
----
- #1712
Update migration script, so that it doesn't update fields where value is already present
=> Update migration script to update createdAt and updatedAt only if it exists

models/tasks.js, test/integration/tasks.test.js
Reverts Real-Dev-Squad/website-backend#1721
This requires index and is breaking the feature
=> Revert "I1720 change task orderby desc order"

models/tasks.js, test/integration/tasks.test.js
Reverts Real-Dev-Squad/website-backend#1725
=> Revert "Revert "I1720 change task orderby desc order""

models/tasks.js, test/integration/tasks.test.js
Date: 26-11-23
----
- closes #1731
Fix the Firestore query to get overdue tasks and filter based on title after adding the default order of updatedAt
Breaking changes (If your feature is breaking/missing something, please mention pending tickets)
=> Update paginated tasks queries and refactor model code

models/tasks.js
Date: 27-11-23
----
- #1731 
Removed order from overdue query and removed title filtration from overdue, as Firestore will give an error when trying to fetch as multiple where conditions are used
=> Update /task model function

config/custom-environment-variables.js
Date: 1-12-23
----
Set env key for corn job private key
=> Set key from env

models/discordactions.js, test/integration/discordactions.test.js, test/unit/models/discordactions.test.js, utils/users.js
Date: 7 Dec 2023
Developer Name: @Ajeyakrishna-k  @bharati-21 
----
Api failed when a single user's details were missing while update their discord nickname. This fix handles those errors gracefully and updates remaining users discord names.
[
](url)
=> Fix api failure when a single user discord details were not present

utils/tasks.js
Date: 12 Dec 2023
----
Updates ts import 
=> Updates ts import 

models/taskRequests.js
=> Fix issue html url

routes/extensionRequests.js, test/integration/extensionRequests.test.js
Date: 31 December 2023
----
- https://github.com/Real-Dev-Squad/website-backend/issues/1638
Removes super user authorization for extension requests
=> Removes super user authorization for extension requests

controllers/questions.ts, middlewares/validators/questions.ts
Fixed the import problem while importing with file extension .ts
=> hotfix: importing with file extension problem

controllers/questions.ts, middlewares/validators/questions.ts, models/questions.ts
Remove logger import statements from questions files
=> Remove logger import statement

config/staging.js
Update discord ID with RDS test server's general channel
=> Update discord id with RDS test server's general channel

typeDefinitions/task-requests.ts, utils/task-requests.ts
Date: 4 January 2024
----
- Fixes errors when running on typescript strict mode
=> Fixes types errors in task requests

controllers/auth.js, test/integration/auth.test.js
- add issue ticket number here e.g `#923`
Id devMode do not do not redirect
=> Id devMode do not do not redirect

middlewares/validators/user.js
Date: `change date here`
Developer Name: `developer name here`
----
- add issue ticket number here e.g `#923`
Fix product_manager validator
=> Fix product_manager validator

.gitattributes
Configuration change
Adds .gitattributes to set text eof to lf
=> Add .gitattributes for end of line to set to lf

services/githubService.js
- #1513 
Fix for inactive API which return inactive user based on last pr merged
=> fix: inactive user api

controllers/extensionRequests.js, models/logs.js, test/integration/extensionRequests.test.js
Date: 31 Jan 2024
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/website-dashboard/issues/682
Extension logs should now be generated even without the dev flag.
=> Feat : Removed feature flag

middlewares/validators/requests.ts, routes/index.ts, routes/requests.ts, test/integration/requests.test.ts, test/unit/middlewares/request.test.ts, types/oooRequest.d.ts
This is the last PR for creating an OOO  status request. in this pR added a new generic rote named `/requests` and used OOO requests middleware, model, and controller to create OOO requests
**Test Coverage:**
| File           | Coverage | Statements | Branches | Functions | Lines |
| -------------- | -------- | ---------- | -------- | --------- | ----- |
| requests.ts    |   88.88% |         50 |      100 |      87.5 |    14 |
**Screenshots:**
=> Added new route for create ooo request

constants/tasks.ts, controllers/tasks.js, routes/tasks.js, test/integration/tasks.test.js
[https://github.com/Real-Dev-Squad/website-backend/issues/1855]
The purpose of this PR is to add a new status called BACKLOG.This status can only be applied by the superuser . There were certain changes done in the codebase as per this PR [https://github.com/Real-Dev-Squad/website-backend/pull/1756] that were removed because they were no longer needed . 
A new status is added called BACKLOG
This closes #1855
=> Added a new status : BACKLOG

constants/oooRequest.ts, controllers/oooRequests.ts, controllers/requests.ts, middlewares/validators/oooRequests.ts, middlewares/validators/requests.ts, models/oooRequests.ts, routes/requests.ts, test/fixtures/oooRequest/oooRequest.ts, test/integration/authorizeUsersAndService.test.ts, test/integration/requests.test.ts, test/unit/middlewares/oooRequests.test.ts, test/unit/middlewares/request.test.ts, test/unit/models/requests.test.ts, types/oooRequest.d.ts
- https://github.com/Real-Dev-Squad/website-backend/issues/1877
In this PR added a new model, middleware, and controller to update the OOO request.
<details>
</details>
- https://github.com/Real-Dev-Squad/website-backend/pull/1879
<details>
</details>
=> FEAT:  API for update OOO requests

models/requests.ts, test/integration/requests.test.ts, test/unit/middlewares/requests.test.ts, test/unit/models/requests.test.ts
Date: 10/04/2024
Developer Name: Palak Gupta
---
closed #1874 
<details>
</details>
Unit test
----------------------------------------|---------|----------|---------|---------|-----------------------------
File                                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                              
----------------------------------------|---------|----------|---------|---------|-----------------------------
/middlewares/validators
oooRequests.ts                        |     100 |      100 |     100 |     100 |            
requests.ts                           |    91.3 |       50 |     100 |   89.74 | 15,24,44,53        
/models
requests.ts …
=> Tests/requests 2: Test cases added for GET /requests related methods

controllers/users.js, controllers/usersStatus.ts, models/usersStatus.ts, routes/index.ts, routes/users.js, routes/usersStatus.ts, test/fixtures/usersStatus/usersStatus.js, test/integration/restricted.test.js, test/integration/users.test.js, test/integration/usersStatus.test.js, test/unit/middlewares/contentTypeCheck.test.js
Date: 19/02/2024
---
Closes #1905 
Re-implement the GET /users/status/self and GET /users/status/:userId routes in the GET /user/status/self and GET /user/status/:userId routes. The PR also includes the latest changes in develop.
<details>
</details>
<details>
</details>
=> Re-implement the GET /users/status/self and GET /users/status/:userId routes

constants/userStatus.ts, models/userFutureStatus.ts, types/oooRequest.d.ts, types/userFutureStatus.d.ts
- Added model functions to create and get user future status
<details>
</details>
<details>
</details>
=> Added model function to create and get user future status

controllers/requests.ts, models/requests.ts
Closes #1920
In this PR, we are creating a new user future status document when OOO request is approved. This will be used to update the user status when the OOO request is active.
<details>
OOO requested 
OOO request approved
User future staus doc created
</details>
**Test Coverage**
| File        | Statements Covered | Branches Covered | Functions Covered | Lines Covered | Lines Missed |
|-------------|--------------------|------------------|-------------------|---------------|--------------|
| requests.ts | 93.1               | 75               | 100               | 92.3          | 24,76,143-144|
=> Creating user future status data when OOO request is approved

config/default.js, config/production.js, constants/authorities.ts, controllers/auth.js, models/users.js, test/integration/auth.test.js
Date: 
Developer Name: @bhtibrewal 
---
https://github.com/Real-Dev-Squad/website-backend/issues/1923
```
set a new cookie-v2 with the configuration 
const cookieOptions = {
domain: rdsUiUrl.hostname,  // .realdevsquad.com
expires: new Date(Date.now() + config.get("userToken.ttl") * 1000),
httpOnly: true,
secure: true,
sameSite: "lax",
};
```
<details>
</details>
</details>
=> cookie v2 containing role and userId

controllers/requests.ts, middlewares/validators/requests.ts, models/requests.ts, test/integration/requests.test.ts, test/unit/models/requests.test.ts, types/oooRequest.d.ts
Closes #1925 
Implemented pagination functionality for the `/requests` endpoint to enhance usability and performance. Changes include:
- Added pagination support allowing for easier navigation and management of large datasets.
- Set default page size to 5 for initial response.
- Included parameters for filtering requests by `requestedBy`, `state`, and `type`.
- Users can specify the page number to retrieve.
Documentation has been updated to reflect the changes made.
Local testing has been performed during development.
<details>
<summary>Get by 'page'</summary>
</details>
<details>
<summary>Get by 'next' and 'prev'</summary>
</details>
<details>
<summary>Get by 'id'</summary>
</details>
<details>
<summary>Get by 'state' and 'type'</summary>
</details>
<details>
<summary>Get by …
=> feat: added feature to get paginated requests

test/unit/utils/users.test.js, utils/users.js
Date: 6 March 2024
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/website-backend/issues/1930
This is a temporary fix. Will update the fix once we start storing discord roles in the database.
Technically no, but it won't affect the actual flow in any case.
NA
=> Feat : Converting maven's first & last name to uppercase

test/fixtures/discordactions/discordactions.js, test/integration/discordactions.test.js
Date: 9 March 2024
Developer Name: Joy Gupta
NA
Fixed failing test cases on develop
=> bugFix : Fixed failing test cases for discord groups

controllers/tasks.js, test/integration/tasks.test.js
Date: 14 Mar 24
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-my/issues/554
This PR adds restrictions for task status change according to this issue ticket https://github.com/Real-Dev-Squad/website-my/issues/554
[Screencast from 14-03-24 06:55:19 AM IST.webm](https://github.com/Real-Dev-Squad/website-backend/assets/68867418/0bf60156-97bb-4564-a3f5-dc72db25a843)
<details>
</details>
Unit tests
Integration tests
<details>
</details>
=> Modified task status flow 

middlewares/validators/task-requests.js, models/taskRequests.js, test/fixtures/task-requests/task-requests.js, test/unit/models/task-requests.test.js
Date: 24th March 2024
Developer Name: Tushar Goel
Add markdownEnabled field in taskRequest models
https://github.com/Real-Dev-Squad/website-status/issues/1162
<details>
</details>
<details>
</details>
=> Add markdownEnabled in taskRequest models

constants/logs.ts, models/logs.js, test/integration/logs.test.js, test/unit/models/logs.test.js, test/unit/utils/logs.test.js, utils/logs.js
Date: 24/04/24
Developer Name: Palak Gupta
---
closes https://github.com/Real-Dev-Squad/website-dashboard/issues/700
Refactored the code for formatting the data for activity feed. 
<details>
</details>
----------------------------------------|---------|----------|---------|---------|-----------------------------
File                                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                              
----------------------------------------|---------|----------|---------|---------|-----------------------------                                                           
/models       
logs.js                               |   82.44 |    64.61 |     100 | …
=> backend/activity-feed: refactor code and add test cases

controllers/usersStatus.ts, middlewares/authorizeOwnOrSuperUser.ts, middlewares/validators/usersStatus.ts, models/usersStatus.ts, routes/usersStatus.ts, test/integration/usersStatus.test.js
Date: 08/04/2024
---
Closes #1994 
PR was created to implement a new user status batch and update API. Implemented them but with a small issue which will be fixed in the next PR. Tests are also failing as some tests are failing in the develop branch which are out of the scope of this PR.
=> Reimplement Update API of User Status

.github/workflows/test.yml
Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>
=> Fixed build issues for Failing Test cases 

controllers/external-accounts.js, controllers/progresses.js, models/tasks.js, test/fixtures/discordResponse/discord-response.js, test/integration/external-accounts.test.js, test/integration/progressesTasks.test.js, test/integration/progressesUsers.test.js, test/unit/utils/sendTaskUpdate.test.js, utils/sendTaskUpdate.js
Date: 22/04/2024
Developer Name: @MehulKChaudhari @tejaskh3 
---
#2005 
#2015 
- Reimplement the orphan tasks filtration feature to keep data consistent. filter tasks while marking user archived true.
- We need to send the task progress update on the discord tracking channel, For that we need to connect the discord-slash-command's /task/update API with the backend.
- Staging test screenshot for #2005
- staging test for #2015
=> Dev to main sync. 

controllers/progresses.js, test/unit/utils/sendTaskUpdate.test.js, utils/sendTaskUpdate.js
Date: 26 April, 2024
Developer Name: Tejas
---
#2015 
We need to send the task progress update on the discord tracking channel, For that we need to connect the discord-slash-command's **/task/update API** with the backend.
The API is already there working fine, even on prod. But we need to modify the message format. So, this PR covers that.
- current 
-new one
</details>
</details>
=> feat: add fields to the util

controllers/progresses.js, models/progresses.js, test/unit/utils/sendTaskUpdate.test.js, utils/progresses.js, utils/sendTaskUpdate.js
Date: 2 May, 2024
Developer Name: Tejas
---
#2025
This PR adds a taskTitle field in the sendTaskUpdate util which sends updates on /task/update, which can later be used as a hyperlink.
</details>
| progresses util | progresses model |
|---------|---------|
| ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/070f18a3-7e03-4e12-a8d9-2c1cba3bb9da) | ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/6ba59d81-fcd7-4cb9-a8bf-3f4cc2cec0f3) |
| progresses controller | sendTaskupdate util |
|---------|---------|
| ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/dc1adc14-1b49-463d-8746-eee3415f81a9) | ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/79cb70dc-3d5c-4720-9558-2cf1dd01bd0f) |
| Image …
=> add taskTitle field to sendTaskUpdate util

utils/progresses.js
Date: 6 May, 2024
Developer Name: Tejas
---
#2025
This PR is updating the argument we are passing for the task/update API.
</details>
| progresses util | progresses model |
|---------|---------|
| ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/070f18a3-7e03-4e12-a8d9-2c1cba3bb9da) | ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/6ba59d81-fcd7-4cb9-a8bf-3f4cc2cec0f3) |
| progresses controller | sendTaskupdate util |
|---------|---------|
| ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/dc1adc14-1b49-463d-8746-eee3415f81a9) | ![image](https://github.com/Real-Dev-Squad/website-backend/assets/98630752/79cb70dc-3d5c-4720-9558-2cf1dd01bd0f) |
| Image 5 |
|---------|
| …
=> New branch

controllers/extensionRequestsv2.ts, controllers/oooRequests.ts, controllers/requests.ts, middlewares/validators/oooRequests.ts, middlewares/validators/requests.ts, models/requests.ts, test/integration/requests.test.ts, test/unit/middlewares/oooRequests.test.ts, test/unit/models/requests.test.ts, types/oooRequest.d.ts, types/requests.d.ts
- #2035 
- In this PR, I have implemented the PUT method for extension requests in the `/request` API endpoint.
- `controllers/extensionRequestsv2.ts` - Added new controller to approve or reject extension requests.
- `controllers/oooRequests.ts` - Moved the logic for approving or rejecting OOO requests to a separate controller.
- `controllers/requests.ts` - Removed the logic for approving or rejecting OOO requests and added switch case for extension requests and OOO requests.
- `middlewares/validators/oooRequests.ts` - Removed the validation logic for approving or rejecting OOO requests.
- `middlewares/validators/requests.ts` - Added universal validation logic for approving or rejecting all types of requests.
- `models/requests.ts`: Added new parameter type to update requests.
- …
=> Implement PUT Method for Extension Requests in `/request` Endpoint

controllers/tasks.js, middlewares/validators/tasks.js, models/tasks.js, test/integration/tasks.test.js, test/unit/utils/tasks.test.js, utils/tasks.js
Added support for completed status in update API
Date: May 7 2024
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-status/issues/1197
Made a change in GET /tasks API to fetch both COMPLETED and DONE status simultaneously.
GET /tasks
[screen-capture (24).webm](https://github.com/Real-Dev-Squad/website-backend/assets/68867418/35e3afd1-d80a-4f78-9396-cedebfb62bb9)
<details>
</details>
<details>
</details>
=> Added support for done completed status in get tasks API,

controllers/extensionRequestsv2.ts, controllers/oooRequests.ts, controllers/requests.ts, controllers/tasks.js, middlewares/validators/oooRequests.ts, middlewares/validators/requests.ts, middlewares/validators/tasks.js, models/requests.ts, models/tasks.js, test/integration/requests.test.ts, test/integration/tasks.test.js, test/unit/middlewares/oooRequests.test.ts, test/unit/models/requests.test.ts, types/oooRequest.d.ts, types/requests.d.ts, utils/tasks.js
Date: 05/13/2024
Developer Name:  @sahsisunny @skv93-coder  
---
- #2035
- https://github.com/Real-Dev-Squad/website-status/issues/1197
- #2037
- https://github.com/Real-Dev-Squad/website-backend/pull/2036
<details>
</details>
=> Dev to main sync 

controllers/tasks.js, models/tasks.js, routes/tasks.js, test/integration/tasks.test.js
…(#2040)
* add: one-time script to filter unfinished tasks from archived users.
---------
Date: 22/May/2024
Developer Name: @MehulKChaudhari 
---
- https://github.com/Real-Dev-Squad/todo-action-items/issues/215
One time script to update status of orphan task to `BACKLOG`.
Staging tested
=> Dev to main sync, One time script to mark orphanTasks as backlog

controllers/usersStatus.ts, middlewares/validators/usersStatus.ts, models/usersStatus.ts, routes/usersStatus.ts, test/fixtures/usersStatus/usersStatus.js, test/integration/usersStatus.test.js, utils/userStatus.js
Date: 21/05/2024
Developer Name: @lakshayman  
---
#1911 
Batch and update patch requests reimplemented.
=> Implemented batch and update patch requests

controllers/tasks.js, models/tasks.js, test/integration/tasks.test.js, test/unit/middlewares/tasks-validator.test.js, test/unit/utils/transformQuery.test.js, utils/tasks.js
- #1359
In the PR removed dev FF from /tasks API and tests.
<details>
</details>
<details>
| File                        | Statements (%) | Branches (%) | Functions (%) | Lines (%) | Missing Lines                                   |
|-----------------------------|----------------|--------------|---------------|-----------|------------------------------------------------|
| controllers/tasks.js        | 84.1           | 81.25        | 93.54         | 83.75     | 5, 388, 411-412, 435-436, 441-458, 483-484, 510, 516 |
| models/tasks.js             | 52.36          | 52.48        | 52.3          | 52.9      | 0, 521, 549-550, 578, 589-590, 607, 651-676, 681-700 |
</details>
=> Remove FF from /task API and fix tests

controllers/users.js, routes/users.js, test/fixtures/user/user.js, test/integration/users.test.js
Date: 06/08/2024
---
https://github.com/Real-Dev-Squad/website-dashboard/issues/758
This API returns how many users and developers are verified and blocked.
<details>
</details>
=> Added an API for identity stats

README.md
Date:  18 Aug 2024
Developer Name: Shubham Raj
---
#2073
Changes the anchor link and updates the link to point to website-api-contract
=> [Fix] Broken Link in README.md

middlewares/checkCanGenerateDiscordLink.ts, test/integration/discordactions.test.js
- closes #2077 
Here change the discord invite validator condition to allow users who have application status approved and generating before 25-08-2024 to generate it
and will fix the condition and more test  
by attaching issue ticket
https://github.com/Real-Dev-Squad/website-backend/issues/2078
<details>
</details>
<details>
</details>
=> Change discord link generate validator condition

controllers/applications.ts, models/applications.ts, routes/applications.ts
<details>
</details>
<details>
</details>
=> Migration script to add status pending in applicants collection

models/applications.ts
- close #2084
<details>
</details>
<details>
</details>
=> Revert: hotfix to query application by createdAt

controllers/external-accounts.js
Date: 28 Aug 2024
Developer Name: Prakash Sir
---
https://github.com/Real-Dev-Squad/website-backend/issues/2099
marking Archive false when user runs /verify command 
<details>
</details>
<details>
</details>
=> marked inDiscord: true, archived: false on /verify command 

controllers/users.js, test/integration/users.test.js
Date: 18-08-2024
---
Updated users' self patch call to let the developers with incomplete details update their profiles using the API.
<details>
</details>
=> Fixed users self patch API for new users

middlewares/validators/user.js, test/integration/users.test.js
- closes #2114 
Allow username characters up to 32 character so the users with large first name, last name can generate username
<details>
</details>
<details>
</details>
=> Fix username character limit

middlewares/checkCanGenerateDiscordLink.ts, test/integration/discordactions.test.js
- closes #2119 
In this PR discord, the invite generation check based on the date is removed
<details>
</details>
<details>
</details>
=> Remove discord generation check on date

controllers/users.js, models/users.js, routes/users.js, test/integration/users.test.js, utils/users.js
- closes #2100
<details>
</details>
=> Migration script to update username

models/users.js, routes/users.js, test/integration/users.test.js
#2100 
In this PR script will run on a user with no first or last name 
<details>
</details>
=> Fix Username Migration script to run on users with no first/last name

models/discordactions.js, test/fixtures/discordResponse/discord-response.js, test/fixtures/discordactions/discordactions.js, test/integration/discordactions.test.js, test/integration/external-accounts.test.js, test/unit/models/discordactions.test.js
Reverts Real-Dev-Squad/website-backend#2127
=> Revert "Mavens getting listed in idle,idle7d+"

models/users.js
- closes #2163 
Fix users first name and last name in lower case due to firestore limitations
<details>
</details>
=> Fix users firstname and lastname in lower case

middlewares/validators/user.js, test/unit/middlewares/user-validator.test.js
- closes #2167 
Make first name and lastname to lower case when new users join and update through /self
<details>
</details>
=> Make firstname and lastname to lowercase

controllers/discordactions.js, test/integration/discordactions.test.js
---
Closes #2128 
1. Remove the 404 error when `dev=false`
2. Remove `dev` FF from integration tests for this API
NA
NA
=> Remove dev feature flag for /discord-actions/nicknames/sync API

controllers/applications.ts, middlewares/validators/application.ts, models/applications.ts, test/integration/application.test.ts, test/unit/middlewares/application-validator.test.ts, test/unit/models/application.test.ts
Date: 23/09/2024
Developer Name: Kavya Rishi 
---
Closes: https://github.com/Real-Dev-Squad/website-dashboard/issues/825
A new functionality was added to count the total number of applications that match the given status.
This was achieved by introducing a countQuery, which fetches all documents that match the status
<details>
</details>
<details>
Added them below
</details>
=> enhancement: adding filtered applications count 

models/auctions.js, services/dataAccessLayer.js, utils/users.js
Date: 8 Oct, 2024
Developer Name: Pankaj Sha
---
- closes #2147 
This PR refactors user's utility functions to use data-access layer.
<details>
</details>
=> Refactor user utility functions to use data-access layer

test/integration/taskRequests.test.js, utils/task-requests.ts
Date: 26-10-2024
Developer Name: vinit
---
- closes #2232 
The task request API in staging is giving 500 as some fields are missing in the user doc
<details>
</details>
=> [BUG] No username issue in task-request API

controllers/users.js, test/integration/users.test.js
Date: 28-Oct-2024
Developer Name: @vikasosmium 
---
- Closes #2234 
1. Removed dev feature flag from /users?profile=true&dev=true
- Documentation PR https://github.com/Real-Dev-Squad/website-api-contracts/pull/196
<details>
</details>
<details>
</details>
=> Remove feature flag from /users?profile=true API Endpoint

config/custom-environment-variables.js
Date: 19th Nov
Developer Name: Vikhyat
---
This PR resolves the error faced in staging for the discord command developed by me `/grant-aws-access`, we were facing this issue when running this in stgaging, this is becuase in the `node-config` the values were being set as obj with name field as the actual value
- Output of the command, ran in my discord server
- ENVs - `custom envs config file`
- `default config file`
- Didn't define these in local / staging / production ENV config file
- `.env file` 
- Printing the env values from `node-config` package
- ENV values printed in config 
<details>
</details>
<details>
</details>
=> Fix: Changed the AWS config env variables from object to string

routes/discordactions.js, test/integration/discordactions.test.js
Date: 03 Dec 2024
Developer Name: @VaibhavSingh8 
---
- Closes #2280 
This PR removes the dev feature flag middleware from DELETE "/groups/:groupId" API as the issue has been tested on production, hence requires dev flag removal
<details>
https://github.com/user-attachments/assets/d75e8b70-a943-429f-86d4-181ed4f45814
</details>
<details>
</details>
=> Remove dev feature flag  from DELETE "/groups/:groupId" API

controllers/stocks.js, middlewares/userAuthorization.ts, models/stocks.js, routes/stocks.js, test/integration/stocks.test.ts, test/unit/middlewares/userAuthorization.test.ts
Date: 09-Dec-2024
---
- #2219 
This PR includes adding one route to fetch User Stocks and a deprecation warning for the old route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/203
**Unit Test**
**Integration**
models
routes
validators
controllers
**Unit**
=> Added New Route to fetch User Stocks

controllers/trading.js, routes/trading.ts, test/integration/trading.test.ts
Date: 16-Dec-2024
---
- #2219 
This PR includes adding one POST route for Trading the Stocks and a deprecation warning for the old route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/205
**Coverage**
=> Added alternative POST route for Trading

controllers/userStatus.js, routes/userStatus.js, test/integration/userStatus.test.js
Date: 18-Dec-2024
---
- #2219 
This PR includes updating the PATCH route of UsersStatus /:userId and a deprecation warning for the old self route. This route will now allow both authenticated user and Superuser to use this route to update the status.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/208
**Coverage**
=> Updated UsersStatus /:userId PATCH Endpoint

controllers/users.js, middlewares/conditionalMiddleware.ts, routes/users.js, test/integration/users.test.js, test/unit/middlewares/conditionalMiddleware.test.ts
Date: 25-Dec-2024
---
- #2219 
This PR includes updating the PATCH route of Users /users/:userId and a deprecation warning for the old self route. This route will now allow superuser to approve the profilediff and authenticated user to update their profile data.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/211
**Unit Test**
**Unit Test Coverage**
**Integration Test Coverage**
=> Updated /users/:userId PATCH Endpoint

routes/tasks.js, test/fixtures/tasks/tasks.js, test/fixtures/user/user.js, test/integration/tasks.test.js, test/unit/models/tasks.test.js, test/unit/services/tasks.test.js, test/unit/services/users.test.js
Date: 27-Dec-2024
---
- #2219 
This PR includes adding one PATCH route of Tasks assignment /tasks/assign/:userId and a deprecation warning for the old self route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/213
**Integration Test Coverage**
=> Added /tasks/assign/:userId PATCH Endpoint

routes/tasks.js, test/integration/tasks.test.js
Date: 27-Dec-2024
---
- #2219 
This PR includes adding one PATCH route of Tasks where the users will be able to update the status and percentage of their task and a deprecation warning for the old self route.
- Doc Link https://github.com/Real-Dev-Squad/website-api-contracts/pull/214
**Integration Test Coverage**
=> Added task status PATCH endpoint

test/integration/onboardingExtension.test.ts, test/unit/middlewares/onboardingExtensionRequestValidator.test.ts, test/unit/middlewares/skipAuthenticateForOnboardingExtension.test.ts, test/unit/utils/requests.test.ts
Date: 20 Dec, 2024
---
This PR contains the unit and integration tests for create onboarding extension request api.
<details>
</details>
Feature PR #2307
=> Add tests for create onboarding extension request api

yarn.lock
Date: 09-Jan-2024
---
- #2342  
This PR addresses the repeated PRs raised by the Renovate bot for updating package dependencies. Updating all package dependencies to their latest compatible versions helps streamline the dependency management process and improve overall efficiency.
**Unit Test**
=> Chore Fix: Consolidate and Update Dependency Versions

yarn.lock
Reverts Real-Dev-Squad/website-backend#2341
=> Revert "Chore Fix: Consolidate and Update Dependency Versions"

models/taskRequests.js, test/unit/models/task-requests.test.js
Date: `12th January, 2025`
Developer Name: @Achintya-Chatterjee 
---
- Closes #2327 
This change addresses the issue where the `startedOn` field was being set incorrectly. The fix ensures that `startedOn` is derived directly from the `createdAt` timestamp of the task request during the approval process, maintaining consistency.
<details>
</details>
<details>
</details>
=> fix: negligent tagging instead of proposedStartDate, we are using createdAt

controllers/requests.ts
Date: 19 Jan, 2025
---
- Closes #2360 
This PR removes redundant function call for onboarding extension requests.
<details>
</details>
<details>
</details>
=> Fix: Removes redundant function call for onboarding extension request

test/unit/services/onboardingExtension.test.ts
Date: 26 Jan, 2025
---
- Closes #2368 
This PR fixes flaky test exists in PR #2335.
<details>
</details>
<details>
</details>
=> Fix flaky test present in PR[2335]

controllers/onboardingExtension.ts, middlewares/skipAuthenticateForOnboardingExtension.ts, test/integration/onboardingExtension.test.ts, test/unit/middlewares/skipAuthenticateForOnboardingExtension.test.ts
Date: 17 Feb 2025
Developer Name: @mbramani
---
-  Closes #2376
- Removed feature flag for the following onboarding extension request features:
- `POST /requests`
- `PATCH /requests/:id`
- `PUT /requests/:id` (Approve/Reject)
- Discord command `/onboarding-extension`  
- Users can now access these features without the feature flag.  
<details>
https://github.com/user-attachments/assets/a1bc905f-96bd-4a5d-8c3d-10c2578def82
</details>
<details>
</details>
=> chore: remove feature flag onboarding extension

models/progresses.js, test/integration/progressesTasks.test.js, test/integration/progressesUsers.test.js
Date: 13 Feb , 2025
Developer Name: @AnujChhikara 
---
- [#1331](https://github.com/Real-Dev-Squad/website-status/pull/1330)
- Remove the ?dev=true feature flag from the Get Progresses API to always include the userData field.
<details>
</details>
<details>
</details>
=> Chore: Remove feature flag from Get Progresses API

test/fixtures/oooRequest/oooRequest.ts, test/integration/onboardingExtension.test.ts, test/integration/requests.test.ts
Date: 14-March-2025
Developer Name: @vikasosmium 
---
- Closes #2388 
- This PR fixes failing Integration test due to date range calculation and authentication token expiry.
<details>
</details>
<details>
- Unit Test
- Integration Test
</details>
=> Fix: Integration test due to date range calculation & auth token expiry

constants/progresses.ts, controllers/progresses.js, test/integration/progressesTasks.test.js
Date: 25 March, 2025
---
- Closes #2393 
This PR adds a check which restricts archived users to write progress of a task.
- The  fix is not under feature flag as this is a minor fix without breaking change which further prevent to make changes in status site to test it with dev flag.
<details>
<summary>Working video</summary>
[screen-capture (3).webm](https://github.com/user-attachments/assets/2deeab8d-3138-4849-8a26-bbb242a7474c)
</details>
<details>
</details>
API contract PR - https://github.com/Real-Dev-Squad/website-api-contracts/pull/227
=> Restrict archived users to write progress of a task

controllers/impersonationRequests.ts, middlewares/validators/impersonationRequests.ts, models/impersonationRequests.ts, routes/impersonation.ts, routes/index.ts, services/impersonationRequests.ts, types/impersonationRequest.d.ts
Date: 7/06/2025
Developer Name: Suvidh Kaushik
---
- Closes: #2200 
- This PR contains the route and logic for the creation of impersonation requests
- **This test PR's are #2440 and #2441**
- **This PR should be merged before its corresponding test PR**
- The PR for API contract is present here [PR](https://github.com/Real-Dev-Squad/website-api-contracts/pull/237)
<details>
<summary>Recordings</summary>
**Creation of Impersonation Request**
https://github.com/user-attachments/assets/cab9a514-d800-4ce5-b9a4-172c35c2ed31
**dev feature flag and User not found case:**
https://github.com/user-attachments/assets/a4241574-d919-47e2-a291-14c3fb5eb5dd
**Impersonation Not Completed Case**
https://github.com/user-attachments/assets/c0e4350b-d39f-40ac-a1bf-a090b0e55c3b
**Request already pending …
=> feat: add API to create impersonation request

test/fixtures/impersonation-requests/impersonationRequests.ts, test/unit/middlewares/impersonationRequests.test.ts, test/unit/models/impersonationRequests.test.ts, test/unit/services/impersonationRequests.test.ts
Date: 8/06/2025
Developer Name: Suvidh Kaushik
---
- Closes: #2200 
- This PR contains the unit tests for the model, validator and services of the create impersonation request logic
- **This PR must be merged after the Feature PR -  #2439** 
- **The import errors and build fail is because the feature PR has not been merged yet** 
<details>
N/A
</details>
<details>
**Model Unit Test Coverage**
**Validator Unit Test Coverage**
**Services Unit Test Coverage**
</details>
Design Doc - [LINK](https://docs.google.com/document/d/1Qt0-knoFEWDl6Gdxr0W1xhPy87H-ixwj9Y55Q0bKMUo/edit?tab=t.0#heading=h.w1nbw3goorza)
PRD - [LINK](https://docs.google.com/document/d/1KI7zp81vevaIX3nDNgTsCHDY1iWmad-XFaVgEi3nH2Q/edit?tab=t.0)
Add unit tests for …
=> test/ unit tests for create Impersonation Requests

test/unit/middlewares/impersonationRequests.test.ts, test/unit/models/impersonationRequests.test.ts
Date: 12/06/2025
Developer Name: Suvidh Kaushik
---
- Closes: #2200 
- This PR contains the unit tests for the model, validator of the get Impersonation requests logic
- **This PR must be merged after the Feature PR - #2442 and create route #2439 ** 
- **The import errors and build fail is because the feature PR has not been merged yet** 
<details>
N/A
</details>
<details>
</details>
Design Doc - [LINK](https://docs.google.com/document/d/1Qt0-knoFEWDl6Gdxr0W1xhPy87H-ixwj9Y55Q0bKMUo/edit?tab=t.0#heading=h.w1nbw3goorza)
PRD - [LINK](https://docs.google.com/document/d/1KI7zp81vevaIX3nDNgTsCHDY1iWmad-XFaVgEi3nH2Q/edit?tab=t.0)
Add unit tests for `getImpersonationRequestsValidator` middleware and `impersonationRequests` model …
=> test/ unit tests for get Impersonation requests

test/integration/impersonationRequests.test.ts
Date: 21/06/2025
Developer Name: Suvidh Kaushik
---
- Closes #2200 
- This PR contains the integration tests required for the update Impersonation Requests feature.
-  **This PR will be merged after the feature PR #2446  is merged**
- **The import errors build fail is because our feature PR has not yet been merged**
<details>
N/A
</details>
<details>
</details>
- Design Doc - [LINK](https://docs.google.com/document/d/1Qt0-knoFEWDl6Gdxr0W1xhPy87H-ixwj9Y55Q0bKMUo/edit?tab=t.0#heading=h.w1nbw3goorza)
- PRD - [LINK](https://docs.google.com/document/d/1KI7zp81vevaIX3nDNgTsCHDY1iWmad-XFaVgEi3nH2Q/edit?tab=t.0)
Add integration tests for the update impersonation request feature, including tests for various scenarios such as successful …
=> test/ integration tests for update impersonation request
